Repository adobe/spectrum-css, pull requests merged in 2018-11, with the labels that each got.

#24 ⚡️ #6: improve scroll performance a teeny bit
  tasks/resources/docs/js/docs.js
Labels: performance

#19 📝 readme tweaks
  README.md
Labels: documentation

#29 moved topdoc resources to topdoc template directory, closes #27
  tasks/build-docs.js
  tasks/dev.js
  tasks/gh-pages.js
  tasks/lint.js
  topdoc/README.md
  topdoc/lib/README
  topdoc/resources/css/docs.css
  topdoc/resources/css/vendor/blackboard.css
  topdoc/resources/css/vendor/github.css
  topdoc/resources/css/vendor/normalize.css
  topdoc/resources/css/vendor/rainbow.css
  topdoc/resources/gh-pages-icons.html
  topdoc/resources/gh-pages.html
  topdoc/resources/img/example-ava.jpg
  topdoc/resources/img/example-card-landscape.jpeg
  topdoc/resources/img/example-card-portrait.jpg
  topdoc/resources/img/spectrum_logo_light.svg
  topdoc/resources/js/docs.js
  topdoc/resources/js/vendor/rainbow-custom.min.js
  topdoc/resources/js/vendor/rainbow.linenumbers.min.js
  topdoc/resources/js/vendor/typekit.js
Labels: build, documentation
