Repository adobe/spectrum-css, pull requests merged in 2019-11, with the labels that each got.

#380 fix: removing section margin and fixing responsive image (SDS-3250)
  components/css/responsiveImage.scss
  components/css/section.scss
Labels: bug

#378 fix: opening View Guielines link in new window (SDS-3251)
  components/ResourceCard.js
Labels: bug

#382 fix: normalizing sidebar search input field for Combobox site (SDS-3248)
  components/css/siteSearch.scss
Labels: bug

#384 docs: max the headroom for the headings
  components/PageHeader.js
Labels: documentation

#373 docs: add Rating enhancement to show focus, closes #249
  components/rating/metadata/rating.yml
  site/resources/js/enhancement.js
Labels: Component: Rating
