Repository adobe/spectrum-css, pull requests merged in 2019-10, with the labels that each got.

#301 docs: fix scale switcher dropdown state when resizing window
  site/resources/js/site.js
Labels: enhancement

#351 fix: sidebar width is too small to fit "Spectrum CSS" in large scale
  components/Sidebar.js
  components/css/sidebar.scss
Labels: documentation

#356 fix: revert Checkbox/Radio/Switch color change, fixes #355
  components/checkbox/skin.css
  components/radio/skin.css
  components/toggle/skin.css
Labels: Component: Checkbox

#365 docs: fix dev site Dropdown enhancements in IE 11
  site/resources/js/enhancement.js
  site/resources/js/polyfills.js
Labels: IE Bug, documentation

#364 Visual regression testing optimization
  .travis.yml
  backstop_data/backstop_test.js
  package.json
Labels: testing
