Repository adobe/spectrum-css, pull requests merged in 2019-09, with the labels that each got.

#277 fix: SDS-2298 add correct placeholder opacity for textfields, closes #275
  components/textfield/index.css
Labels: bug

#279 Conventional Commits & Changelogs
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  .travis.yml
  .yarnrc
  README.md
  bundles/spectrum-css-compat/README.md
  bundles/spectrum-css-compat/gulpfile.js
  bundles/spectrum-css-compat/package.json
  bundles/spectrum-css/README.md
  bundles/spectrum-css/gulpfile.js
  bundles/spectrum-css/package.json
  commitlint.config.js
  components/README.md
  gulpfile.js
  lerna.json
  package-lock.json
  package.json
  tools/bundle-builder/dev/index.js
  tools/bundle-builder/docs/index.js
  tools/bundle-builder/index.js
  tools/bundle-builder/lib/depUtils.js
  tools/bundle-builder/lib/dirs.js
  tools/bundle-builder/lib/exec.js
  tools/bundle-builder/package.json
  tools/bundle-builder/release/index.js
  tools/bundle-builder/release/updateDeps.js
  tools/bundle-builder/subrunner/index.js
  tools/component-builder/css/legacyBuild.js
  tools/component-builder/css/lib/postcss-custom-properties-mapping.js
  tools/component-builder/docs/index.js
  tools/conventional-changelog-spectrum/CHANGELOG.md
  tools/conventional-changelog-spectrum/LICENSE.md
  tools/conventional-changelog-spectrum/README.md
  tools/conventional-changelog-spectrum/conventional-changelog.js
  tools/conventional-changelog-spectrum/conventional-recommended-bump.js
  tools/conventional-changelog-spectrum/index.js
  tools/conventional-changelog-spectrum/package.json
  tools/conventional-changelog-spectrum/parser-opts.js
  tools/conventional-changelog-spectrum/templates/commit.hbs
  tools/conventional-changelog-spectrum/templates/footer.hbs
  tools/conventional-changelog-spectrum/templates/header.hbs
  tools/conventional-changelog-spectrum/templates/template.hbs
  tools/conventional-changelog-spectrum/test/fixtures/_ghe-host.json
  tools/conventional-changelog-spectrum/test/fixtures/_known-host.json
  tools/conventional-changelog-spectrum/test/fixtures/_unknown-host.json
  tools/conventional-changelog-spectrum/test/test.js
  tools/conventional-changelog-spectrum/writer-opts.js
  yarn.lock
Labels: blocked by dependency

#271 BackstopJS visual regression testing
  .gitignore
  .travis.yml
  README.md
  backstop.json
  backstop_data/backstop_scenarios.json
  backstop_data/backstop_template/index.html
  backstop_data/backstop_test.js
  backstop_data/engine_scripts/casper/clickAndHoverHelper.js
  backstop_data/engine_scripts/casper/loadCookies.js
  backstop_data/engine_scripts/casper/onBefore.js
  backstop_data/engine_scripts/casper/onReady.js
  backstop_data/engine_scripts/casper/waitForHelperHelper.js
  backstop_data/engine_scripts/chromy/clickAndHoverHelper.js
  backstop_data/engine_scripts/chromy/loadCookies.js
  backstop_data/engine_scripts/chromy/onBefore.js
  backstop_data/engine_scripts/chromy/onReady.js
  backstop_data/engine_scripts/cookies.json
  backstop_data/engine_scripts/onBefore.js
  backstop_data/engine_scripts/onReady.js
  backstop_data/engine_scripts/puppet/injectSpectrumThemeAndScale.js
  backstop_data/engine_scripts/puppet/onReady.js
  backstop_data/packageDependentMap.json
  gulpfile.js
  package.json
  tools/bundle-builder/dev/index.js
  tools/test-builder/index.js
  tools/test-builder/package.json
  tools/test-builder/plugins/scenarioList.js
  yarn.lock
Labels: blocked by dependency

#286 build: fix error handling in subrunner
  tools/bundle-builder/subrunner/index.js
Labels: build

#283 Leave Gallery preview card height to the JS
  components/card/index.css
Labels: Component: Card, bug

#291 docs: make issue report template fields for environment bold
  .github/ISSUE_TEMPLATE/--bug-report.md
  .github/ISSUE_TEMPLATE/--support-request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#285 Temporary site design update for 2.14 release
  components/card/index.css
  components/card/metadata/card.yml
  components/card/skin.css
  components/dropdown/metadata/dropdown.yml
  components/site/index.css
  components/site/skin.css
  gulpfile.js
  package.json
  site/getting-started.pug
  site/includes/example.pug
  site/includes/footer.pug
  site/includes/nav.pug
  site/includes/pageBottom.pug
  site/includes/sidebar.pug
  site/index.pug
  site/resources/css/docs.css
  site/resources/js/Search.js
  site/resources/js/docs.js
  site/resources/js/enhancement.js
  site/resources/js/site.js
  site/templates/siteComponent.pug
  site/util.js
  tools/bundle-builder/docs/index.js
  tools/bundle-builder/lib/exec.js
Labels: documentation
