Repository adobe/spectrum-css, pull requests merged in 2023-05, with the labels that each got.

#1817 fix(contextualhelp): dark mode font color
  components/contextualhelp/index.css
  components/contextualhelp/metadata/contextualhelp.yml
  components/contextualhelp/metadata/mods.md
Labels: bug

#1818 Missing Sections in the components (IMPORTANT)
  site/_data/component.js
  site/_includes/example.njk
  site/_includes/meta-info.njk
  site/_includes/section.njk
  site/assets/css/docs.css
  site/content/components.njk
  site/scripts/getMetadata.js
  yarn.lock
Labels: bug

#1841 fix: resolve missing preview destination
  package.json
Labels: do not merge

#1568 feat(thumbnail)!: migrate tokens
  components/thumbnail/gulpfile.js
  components/thumbnail/index.css
  components/thumbnail/metadata/mods.md
  components/thumbnail/metadata/thumbnail.yml
  components/thumbnail/package.json
  components/thumbnail/skin.css
  components/thumbnail/stories/template.js
  components/thumbnail/stories/thumbnail.stories.js
  components/thumbnail/themes/express.css
  components/thumbnail/themes/spectrum.css
  components/treeview/metadata/treeview.yml
  yarn.lock
Labels: breaking change, released-beta, pending-swc-validation

#1642 feat(rating)!: token migration
  components/rating/gulpfile.js
  components/rating/index.css
  components/rating/metadata/mods.md
  components/rating/package.json
  components/rating/skin.css
  components/rating/stories/rating.stories.js
  components/rating/stories/template.js
  components/rating/themes/express.css
  components/rating/themes/spectrum.css
Labels: breaking change

#1696 feat(slider)!: update slider tokens
  components/fieldlabel/index.css
  components/fieldlabel/metadata/mods.md
  components/fieldlabel/stories/template.js
  components/slider/gulpfile.js
  components/slider/index.css
  components/slider/metadata/mods.md
  components/slider/metadata/slider.yml
  components/slider/package.json
  components/slider/skin.css
  components/slider/stories/slider.stories.js
  components/slider/stories/template.js
  components/slider/themes/express.css
  components/slider/themes/spectrum.css
  site/resources/js/enhancement.js
Labels: breaking change, released-beta, pending-swc-validation

#1831 feat(dropzone)!: migrate tokens
  components/actionbutton/index.css
  components/actionbutton/metadata/mods.md
  components/dropzone/gulpfile.js
  components/dropzone/index.css
  components/dropzone/metadata/dropzone.yml
  components/dropzone/metadata/mods.md
  components/dropzone/package.json
  components/dropzone/skin.css
  components/dropzone/stories/dropzone.stories.js
  components/dropzone/stories/template.js
  components/dropzone/themes/express.css
  components/dropzone/themes/spectrum.css
  components/illustratedmessage/index.css
  components/illustratedmessage/metadata/mods.md
  site/resources/js/enhancement.js
Labels: released-beta, pending-swc-validation

#1897 chore: update auto-updater to configurable version
  .github/workflows/pr-update.yml
  .github/workflows/testing.yml
Labels: skip_vrt
