Repository adobe/spectrum-css, pull requests merged in 2023-08, with the labels that each got.

#1942 feat(menu): migrate to spectrum-tokens + add new features
  components/menu/README.md
  components/menu/gulpfile.js
  components/menu/index.css
  components/menu/metadata/menu.yml
  components/menu/metadata/mods.md
  components/menu/package.json
  components/menu/skin.css
  components/menu/stories/menu.stories.js
  components/menu/stories/template.js
  components/menu/themes/express.css
  components/menu/themes/spectrum.css
  site/resources/js/Search.js
  site/templates/siteComponent.pug
  yarn.lock
Labels: released-beta

#2068 fix(popover): docs site popover bug fix
  site/resources/js/enhancement.js
Labels: skip_vrt

#2094 chore: Update dependabot groups
  .github/dependabot.yml
Labels: skip_vrt

#1943 feat(clearbutton)!: migrate tokens
  components/clearbutton/gulpfile.js
  components/clearbutton/index.css
  components/clearbutton/metadata/clearbutton.yml
  components/clearbutton/metadata/mods.md
  components/clearbutton/package.json
  components/clearbutton/stories/clearbutton.stories.js
  components/clearbutton/stories/template.js
  components/clearbutton/themes/express.css
  components/clearbutton/themes/spectrum.css
  components/tag/index.css
  components/tag/metadata/mods.md
  yarn.lock
Labels: released-beta

#2102 chore: update javascript for site to account for removal of focus-ring
  site/resources/js/enhancement.js
Labels: skip_vrt

#1924 refactor(colorslider)!: core tokens migration
  components/colorslider/README.md
  components/colorslider/gulpfile.js
  components/colorslider/index.css
  components/colorslider/metadata/colorslider.yml
  components/colorslider/metadata/mods.md
  components/colorslider/package.json
  components/colorslider/skin.css
  components/colorslider/stories/colorslider.stories.js
  components/colorslider/stories/template.js
  components/colorslider/themes/express.css
  components/colorslider/themes/spectrum.css
Labels: breaking change, released-beta, wip, pending-swc-validation

#2096 feat(underlay)!: diy migration
  components/dialog/stories/dialog.stories.js
  components/dialog/stories/template.js
  components/underlay/gulpfile.js
  components/underlay/index.css
  components/underlay/metadata/mods.md
  components/underlay/package.json
  components/underlay/stories/template.js
  components/underlay/stories/underlay.stories.js
  components/underlay/themes/express.css
  components/underlay/themes/spectrum.css
Labels: released-beta, pending-swc-validation

#1993 chore(popover): update popover stories
  components/actionbutton/index.css
  components/actionmenu/stories/actionmenu.stories.js
  components/actionmenu/stories/template.js
  components/card/stories/card.stories.js
  components/card/stories/template.js
  components/contextualhelp/stories/template.js
  components/dialog/stories/dialog.stories.js
  components/dialog/stories/template.js
  components/illustratedmessage/stories/illustratedmessage.stories.js
  components/illustratedmessage/stories/template.js
  components/picker/stories/picker.stories.js
  components/popover/index.css
  components/popover/metadata/mods.md
  components/popover/metadata/popover.yml
  components/popover/stories/popover.stories.js
  components/popover/stories/template.js
  components/tray/stories/template.js
  components/tray/stories/tray.stories.js
  components/well/stories/template.js
  components/well/stories/well.stories.js
  tools/preview/main.js
  tools/preview/package.json
  tools/preview/preview.js
  yarn.lock
Labels: released-beta
