Repository adobe/spectrum-css, pull requests merged in 2023-11, with the labels that each got.

#2189 fix: exclude passthrough mods from generated mods.md
  components/actiongroup/metadata/mods.md
  components/alertbanner/metadata/mods.md
  components/alertdialog/metadata/mods.md
  components/colorhandle/metadata/mods.md
  components/colorslider/metadata/mods.md
  components/combobox/metadata/mods.md
  components/dropzone/metadata/mods.md
  components/infieldbutton/metadata/mods.md
  components/menu/metadata/mods.md
  components/search/metadata/mods.md
  components/stepper/metadata/mods.md
  components/table/metadata/mods.md
  components/tag/metadata/mods.md
  tasks/mod-extractor.js
Labels: skip_vrt

#2255 chore: support .env template at root
  .env.example
  package.json
  tasks/copy-env-from-root.sh
Labels: skip_vrt

#2221 docs: update pr template testing information
  .github/PULL_REQUEST_TEMPLATE.md
Labels: run_vrt, skip_vrt

#2263 fix(opacitycheckerboard): align token version to latest release
  components/opacitycheckerboard/package.json
  yarn.lock
Labels: skip_vrt

#2198 feat(dropindicator): migrate to spectrum tokens
  components/dropindicator/gulpfile.js
  components/dropindicator/index.css
  components/dropindicator/metadata/mods.md
  components/dropindicator/package.json
  components/dropindicator/stories/template.js
  components/dropindicator/themes/express.css
  components/dropindicator/themes/spectrum.css
  components/tokens/custom-spectrum/custom-dark-vars.css
  components/tokens/custom-spectrum/custom-darkest-vars.css
  components/tokens/custom-spectrum/custom-light-vars.css
Labels: ready-to-merge

#2220 refactor(textfield): invalid and valid padding inline end
  components/textfield/index.css
  components/textfield/metadata/mods.md
Labels: ready-to-merge

#2226 docs(picker): update markup for menu
  components/picker/metadata/picker.yml
Labels: ready-to-merge

#2217 fix(slider): focus state matches spec, supports forced-colors
  components/slider/index.css
  components/slider/metadata/slider.yml
  components/slider/stories/slider.stories.js
  components/slider/stories/template.js
Labels: ready-to-merge

#2270 chore: ci rework
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/--bug-report.md
  .github/ISSUE_TEMPLATE/--support-request.md
  .github/README.md
  .github/actions/file-diff/README.md
  .github/actions/file-diff/action.yml
  .github/actions/file-diff/index.js
  .github/actions/file-diff/package.json
  .github/actions/file-diff/utilities.js
  .github/dependabot.yml
  .github/workflows/build.yml
  .github/workflows/compare-results.yml
  .github/workflows/development.yml
  .github/workflows/lint.yml
  .github/workflows/pr-build-and-deploy.yml
  .github/workflows/pr-update.yml
  .github/workflows/production.yml
  .github/workflows/publish-site.yml
  .github/workflows/testing.yml
  .github/workflows/vrt.yml
  .nvmrc
  .stylelintrc.json
  package.json
  stylelint.config.js
  tasks/mod-extractor.js
  yarn.lock
Labels: ready-for-review

#2287 chore(ci): remove dynamically named ci so we can require it for pull requests
  .github/workflows/build.yml
  .github/workflows/compare-results.yml
  .github/workflows/lint.yml
  .github/workflows/publish-site.yml
  .github/workflows/vrt.yml
Labels: ready-for-review

#2277 feat(tokens)!: migrate package to root; out of components
  .prettierignore
  .stylelintignore
  generator/plopfile.js
  package.json
  site/gulpfile.js
  tasks/clean-up-after-migration.sh
  tokens/CHANGELOG.md
  tokens/README.md
  tokens/custom-express/custom-dark-vars.css
  tokens/custom-express/custom-darkest-vars.css
  tokens/custom-express/custom-large-vars.css
  tokens/custom-express/custom-light-vars.css
  tokens/custom-express/custom-medium-vars.css
  tokens/custom-express/custom-vars.css
  tokens/custom-spectrum/custom-dark-vars.css
  tokens/custom-spectrum/custom-darkest-vars.css
  tokens/custom-spectrum/custom-large-vars.css
  tokens/custom-spectrum/custom-light-vars.css
  tokens/custom-spectrum/custom-medium-vars.css
  tokens/custom-spectrum/custom-vars.css
  tokens/package.json
  tokens/postcss.config.js
  tokens/style-dictionary.config.js
  tokens/utilities/style-dictionary.utils.js
  tools/bundle-builder/dev/index.js
  tools/bundle-builder/docs/README.md
  tools/bundle-builder/docs/index.js
  tools/bundle-builder/lib/depUtils.js
  tools/bundle-builder/package.json
  tools/bundle-builder/subrunner/index.js
  tools/bundle-builder/vars/index.js
  tools/component-builder-simple/package.json
  tools/component-builder/package.json
Labels: run_vrt, ready-for-review

#2279 feat(card): add additional mod properties
  components/card/index.css
  components/card/metadata/mods.md
Labels: run_vrt

#2290 chore(ci): add stricter timeouts to jobs
  .github/workflows/build.yml
  .github/workflows/compare-results.yml
  .github/workflows/lint.yml
  .github/workflows/production.yml
  .github/workflows/publish-site.yml
  .github/workflows/vrt.yml
Labels: skip_vrt, ready-for-review

#2298 chore: add the compare utility
  .gitignore
  README.md
  package.json
  tasks/compare-compiled-output.js
  tasks/templates/compare-listing.njk
  tasks/templates/diff-preview.njk
  yarn.lock
Labels: skip_vrt, ready-for-review

#2303 chore: patch storybook build for ci
  .storybook/main.js
Labels: ready-for-review

#2321 fix(storybook): postcss parsing error for node_modules paths
  .storybook/postcss.config.js
Labels: size-1 XS, run_vrt, storybook, ready-for-review

#2315 fix(radio): focus outline has correct position for rtl
  components/radio/index.css
Labels: run_vrt, ready-to-merge

#2308 fix(steplist): add WHCM for marker
  components/steplist/index.css
Labels: ready-to-merge

#2314 fix(popover): nested storybook example is open and static
  components/popover/stories/popover.stories.js
  components/popover/stories/template.js
Labels: run_vrt
