Repository adobe/spectrum-css, pull requests merged in 2023-04, with the labels that each got.

#1590 feat(tokens)!: Extract RGB color values into their own custom properties [CSS-383]
  .github/workflows/pr-build-and-deploy.yml
  .github/workflows/testing.yml
  COPYRIGHT
  components/expressvars/gulpfile.js
  components/expressvars/package.json
  components/expressvars/tasks/updateDNA.js
  components/pagination/package.json
  components/picker/package.json
  components/search/package.json
  components/searchwithin/package.json
  components/swatch/metadata/mods.md
  components/tokens/config.js
  components/tokens/custom-express/custom-light-vars.css
  components/tokens/custom-spectrum/custom-light-vars.css
  components/tokens/gulpfile.js
  components/tokens/package.json
  components/tokens/postcss.config.js
  components/tokens/style-dictionary.config.js
  components/tokens/utilities/style-dictionary.utils.js
  components/vars/gulpfile.js
  components/vars/package.json
  components/vars/tasks/updateDNA.js
  gulpfile.js
  package.json
  tools/bundle-builder/dev/index.js
  tools/bundle-builder/index.js
  tools/bundle-builder/subrunner/index.js
  tools/preview/package.json
  yarn.lock
Labels: bug, breaking change, run_vrt

#1770 Ensure that all metadata/*.js assets are being loaded on the site into a bundle
  tools/documentation/_data/component.js
  tools/documentation/_includes/meta-info.njk
  tools/documentation/_layouts/pages.njk
Labels: enhancement, javascript

#1767 chore: separate out js functionality for each component
  components/accordion/metadata/enhancement.js
  components/cyclebutton/metadata/enhancement.js
  components/datepicker/metadata/enhancement.js
  components/dial/metadata/enhancement.js
  components/dialog/metadata/enhancement.js
  components/progresscircle/metadata/enhancement.js
  components/slider/metadata/enhancement.js
  components/stepper/metadata/enhancement.js
  components/treeview/metadata/enhancement.js
  tools/documentation/_includes/meta-info.njk
  tools/documentation/_includes/sidenav.njk
  tools/documentation/assets/js/Search.js
  tools/documentation/assets/js/SpectrumPicker.js
  tools/documentation/assets/js/enhancement.js
Labels: documentation, build, enhancement, tech debt

#1774 chore: Validate pathing to the component pages looks right and is loading from navigation with a single click
  tools/documentation/_includes/link-cards.njk
  tools/documentation/_includes/sidenav.njk
  tools/documentation/_layouts/pages.njk
  tools/documentation/assets/js/Search.js
  tools/documentation/assets/js/docs.js
  tools/documentation/content/components.njk
  tools/documentation/content/index.njk
Labels: bug, enhancement

#1777 chore: fix vrt command
  .github/workflows/testing.yml
  package.json
Labels: run_vrt

#1753 feat(colorloupe, colorhandle)!: migrate to core tokens
  components/colorarea/index.css
  components/colorarea/metadata/colorarea.yml
  components/colorhandle/gulpfile.js
  components/colorhandle/index.css
  components/colorhandle/metadata/colorhandle.yml
  components/colorhandle/metadata/mods.md
  components/colorhandle/package.json
  components/colorhandle/skin.css
  components/colorhandle/stories/template.js
  components/colorhandle/themes/express.css
  components/colorhandle/themes/spectrum.css
  components/colorloupe/gulpfile.js
  components/colorloupe/index.css
  components/colorloupe/metadata/colorloupe.yml
  components/colorloupe/metadata/mods.md
  components/colorloupe/package.json
  components/colorloupe/skin.css
  components/colorloupe/stories/colorloupe.stories.js
  components/colorloupe/stories/template.js
  components/colorloupe/themes/express.css
  components/colorloupe/themes/spectrum.css
  components/colorslider/index.css
  components/colorslider/metadata/colorslider.yml
  components/colorwheel/index.css
  components/colorwheel/metadata/colorwheel.yml
  yarn.lock
Labels: released-beta, pending-swc-validation

#1699 feat(illustratedmessage)!: core tokens migration
  components/dropzone/metadata/dropzone.yml
  components/dropzone/stories/dropzone.stories.js
  components/dropzone/stories/template.js
  components/illustratedmessage/gulpfile.js
  components/illustratedmessage/index.css
  components/illustratedmessage/metadata/illustratedmessage.yml
  components/illustratedmessage/metadata/mods.md
  components/illustratedmessage/package.json
  components/illustratedmessage/stories/illustratedmessage.stories.js
  components/illustratedmessage/stories/illustration.svg
  components/illustratedmessage/stories/template.js
  components/illustratedmessage/themes/express.css
  components/illustratedmessage/themes/spectrum.css
  yarn.lock
Labels: breaking change, released-beta, pending-swc-validation

#1805 chore: update README commands; minor ci fixes
  .github/workflows/pr-build-and-deploy.yml
  .github/workflows/testing.yml
  README.md
  package.json
Labels: run_vrt
