Repository adobe/spectrum-css, pull requests merged in 2023-07, with the labels that each got.

#1902 feat(tabs)!: migrate tokens
  components/tabs/gulpfile.js
  components/tabs/index.css
  components/tabs/metadata/mods.md
  components/tabs/metadata/tabs.yml
  components/tabs/package.json
  components/tabs/skin.css
  components/tabs/stories/index.js
  components/tabs/stories/tabs-horizontal-compact.stories.js
  components/tabs/stories/tabs-horizontal-emphasized.stories.js
  components/tabs/stories/tabs-horizontal-quiet.stories.js
  components/tabs/stories/tabs-horizontal.stories.js
  components/tabs/stories/tabs-vertical-compact.stories.js
  components/tabs/stories/tabs-vertical-emphasized.stories.js
  components/tabs/stories/tabs-vertical-quiet.stories.js
  components/tabs/stories/tabs-vertical.stories.js
  components/tabs/stories/tabs.stories.js
  components/tabs/stories/template.js
  components/tabs/themes/express.css
  components/tabs/themes/spectrum.css
  tools/preview/assets/base.css
  tools/preview/assets/index.css
Labels: breaking change, released-beta, pending-swc-validation

#2003 chore: update pr and issue templates
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/--bug-report.md
  .github/ISSUE_TEMPLATE/--documentation-issue.md
  .github/ISSUE_TEMPLATE/--feature-request.md
  .github/ISSUE_TEMPLATE/--support-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yml
Labels: skip_vrt

#1916 feat(opacitycheckerboard)!: new component
  components/colorhandle/index.css
  components/colorhandle/metadata/colorhandle.yml
  components/colorhandle/metadata/mods.md
  components/colorhandle/package.json
  components/colorslider/index.css
  components/colorslider/metadata/colorslider.yml
  components/colorslider/package.json
  components/opacitycheckerboard/README.md
  components/opacitycheckerboard/gulpfile.js
  components/opacitycheckerboard/index.css
  components/opacitycheckerboard/metadata/mods.md
  components/opacitycheckerboard/metadata/opacitycheckerboard.yml
  components/opacitycheckerboard/package.json
  components/opacitycheckerboard/stories/opacitycheckerboard.stories.js
  components/opacitycheckerboard/stories/template.js
  components/opacitycheckerboard/themes/express.css
  components/opacitycheckerboard/themes/spectrum.css
  components/swatch/index.css
  components/swatch/metadata/swatch.yml
  components/swatch/package.json
  components/thumbnail/index.css
  components/thumbnail/metadata/mods.md
  components/thumbnail/metadata/thumbnail.yml
  components/thumbnail/package.json
  yarn.lock
Labels: do not merge, pending-swc-validation, released-alpha

#1940 feat(pickerbutton)!: migrate tokens
  components/picker/package.json
  components/pickerbutton/gulpfile.js
  components/pickerbutton/index.css
  components/pickerbutton/metadata/mods.md
  components/pickerbutton/metadata/pickerbutton.yml
  components/pickerbutton/package.json
  components/pickerbutton/pickerbutton-generated.css
  components/pickerbutton/stories/pickerbutton.stories.js
  components/pickerbutton/stories/template.js
  components/pickerbutton/themes/express.css
  components/pickerbutton/themes/spectrum.css
  components/searchwithin/index.css
  components/searchwithin/metadata/mods.md
  components/searchwithin/stories/template.js
  yarn.lock
Labels: released-beta, pending-swc-validation
