Repository adobe/spectrum-css, pull requests merged in 2023-06, with the labels that each got.

#1907 chore: add prettier configuration
  .prettierignore
  .prettierrc
  package.json
Labels: skip_vrt

#1787 feat: add stylelint
  .github/workflows/linting.yml
  .prettierignore
  .stylelintignore
  .stylelintrc.json
  components/checkbox/index.css
  components/switch/index.css
  package.json
  plugins/README.md
  plugins/stylelint-no-missing-parenthesis/CHANGELOG.md
  plugins/stylelint-no-missing-parenthesis/README.md
  plugins/stylelint-no-missing-parenthesis/index.js
  plugins/stylelint-no-missing-parenthesis/package.json
  plugins/stylelint-no-missing-parenthesis/test.js
  plugins/stylelint-no-missing-var/CHANGELOG.md
  plugins/stylelint-no-missing-var/README.md
  plugins/stylelint-no-missing-var/index.js
  plugins/stylelint-no-missing-var/package.json
  plugins/stylelint-no-missing-var/test.js
  plugins/stylelint-suit-naming-pattern/CHANGELOG.md
  plugins/stylelint-suit-naming-pattern/README.md
  plugins/stylelint-suit-naming-pattern/index.js
  plugins/stylelint-suit-naming-pattern/package.json
  plugins/stylelint-suit-naming-pattern/test.js
  yarn.lock
Labels: enhancement, github_actions

#1761 chore(search)!: core tokens migration
  components/search/gulpfile.js
  components/search/index.css
  components/search/metadata/mods.md
  components/search/metadata/search.yml
  components/search/package.json
  components/search/skin.css
  components/search/stories/search.stories.js
  components/search/stories/template.js
  components/search/themes/express.css
  components/search/themes/spectrum.css
  components/textfield/index.css
  components/textfield/metadata/textfield.yml
  components/textfield/stories/textfield.stories.js
Labels: breaking change, released-beta, pending-swc-validation

#1954 fix: reorder build:all script
  package.json
Labels: run_vrt

#1789 feat(accordion): core token migration
  components/accordion/gulpfile.js
  components/accordion/index.css
  components/accordion/metadata/accordion.yml
  components/accordion/metadata/mods.md
  components/accordion/package.json
  components/accordion/skin.css
  components/accordion/stories/accordion.stories.js
  components/accordion/stories/template.js
  components/accordion/themes/express.css
  components/accordion/themes/spectrum.css
Labels: breaking change, released-beta, pending-swc-validation

#1972 fix(expressvars): slider variable typo
  .prettierignore
  components/expressvars/custom.css
Labels: bug, size-1 XS

#1693 feat(card)!: update cards tokens
  assets/example-ava@2x.png
  components/card/gulpfile.js
  components/card/index.css
  components/card/metadata/card-asset.yml
  components/card/metadata/card-gallery.yml
  components/card/metadata/card.yml
  components/card/metadata/mods.md
  components/card/package.json
  components/card/stories/card.stories.js
  components/card/stories/template.js
  components/card/themes/express.css
  components/card/themes/spectrum.css
  package-lock.json
Labels: breaking change, released-beta, pending-swc-validation

#1979 chore(calendar): storybook fix for today highlighter
  components/calendar/stories/calendar.stories.js
  components/calendar/stories/template.js
Labels: run_vrt

#1980 fix(swatch): specify forced-color style for disabled swatch borders
  components/swatch/index.css
Labels: run_vrt

#1958 fix(colorloupe): border bug
  components/colorhandle/metadata/colorhandle.yml
  components/colorloupe/index.css
  components/colorloupe/metadata/colorloupe.yml
  components/colorloupe/stories/colorloupe.stories.js
  components/colorloupe/stories/template.js
  components/colorslider/metadata/colorslider.yml
Labels: bug, size-1 XS

#1983 fix: tag focus issue solved
  components/tag/index.css
Labels: bug, a11y

#1981 chore(calendar): improve stories
  components/calendar/stories/calendar.stories.js
  components/calendar/stories/template.js
Labels: run_vrt
