Repository adobe/spectrum-css, pull requests merged in 2023-03, with the labels that each got.

#1638 feat: add additional storybook stories
  components/inlinealert/stories/inlinealert.stories.js
  components/inlinealert/stories/template.js
  components/pickerbutton/stories/pickerbutton.stories.js
  components/pickerbutton/stories/template.js
  components/progresscircle/stories/progresscircle.stories.js
  components/progresscircle/stories/template.js
  components/statuslight/stories/statuslight.stories.js
  components/statuslight/stories/template.js
Labels: wip

#1619 feat(colorwheel)!: migrate to core tokens
  components/colorarea/index.css
  components/colorwheel/gulpfile.js
  components/colorwheel/index.css
  components/colorwheel/metadata/colorwheel.yml
  components/colorwheel/metadata/mods.md
  components/colorwheel/package.json
  components/colorwheel/skin.css
  components/colorwheel/stories/colorwheel.stories.js
  components/colorwheel/stories/template.js
  components/colorwheel/themes/express.css
  components/colorwheel/themes/spectrum.css
Labels: released-beta

#1544 refactor(textfield): migrate spectrum tokens
  components/inputgroup/CHANGELOG.md
  components/inputgroup/package.json
  components/pickerbutton/CHANGELOG.md
  components/pickerbutton/index.css
  components/pickerbutton/package.json
  components/stepper/CHANGELOG.md
  components/stepper/gulpfile.js
  components/stepper/index.css
  components/stepper/metadata/stepper.yml
  components/stepper/package.json
  components/stepper/stories/stepper.stories.js
  components/stepper/stories/template.js
  components/stepper/themes/express.css
  components/stepper/themes/spectrum.css
  components/textfield/CHANGELOG.md
  components/textfield/gulpfile.js
  components/textfield/index.css
  components/textfield/metadata/textarea.yml
  components/textfield/metadata/textfield.yml
  components/textfield/package.json
  components/textfield/skin.css
  components/textfield/stories/template.js
  components/textfield/stories/textfield.stories.js
  components/textfield/themes/express.css
  components/textfield/themes/spectrum.css
  yarn.lock
Labels: released-beta, pending-swc-validation

#1673 feat: configure local visual testing with Chromatic
  .github/workflows/testing.yml
  .gitignore
  components/calendar/stories/calendar.stories.js
  package.json
  tools/preview/.env.example
  tools/preview/README.md
  tools/preview/package.json
  yarn.lock
Labels: skip_vrt

#1683 fix(tokens): add 'px' to zero length value for combobox
  components/tokens/package.json
  yarn.lock
Labels: skip_vrt

#1700 chore: adjust chromatic github action
  .github/workflows/testing.yml
  tools/preview/package.json
Labels: run_vrt
