Repository adobe/spectrum-css, pull requests merged in 2023-12, with the labels that each got.

#2276 fix(infieldbutton): focus wont persist after mouse interaction
  components/infieldbutton/index.css
Labels: run_vrt

#2339 chore(ci): error if uncomitted changes found on build
  .github/workflows/build.yml
Labels: size-1 XS, skip_vrt, ready-for-review

#2341 docs(tag): invalid tags should always include icon
  components/tag/metadata/tag.yml
  components/tag/stories/tag.stories.js
  components/tag/stories/template.js
  components/taggroup/metadata/taggroup.yml
Labels: run_vrt, ready-to-merge

#2345 chore(ci): correct data formatting for diff comment
  .github/actions/file-diff/index.js
  .github/actions/file-diff/utilities.js
Labels: size-1 XS, build, skip_vrt, ready-for-review

#2348 chore(ci): deconstruct filemap in workflow
  .github/actions/file-diff/index.js
Labels: size-1 XS, skip_vrt, ready-for-review

#2300 fix(stepper): no longer touches InfieldButton classes
  components/infieldbutton/index.css
  components/infieldbutton/metadata/mods.md
  components/stepper/index.css
  components/stepper/metadata/mods.md
  components/stepper/themes/express.css
  components/stepper/themes/spectrum.css
Labels: run_vrt

#2361 chore(ci): clean file diff output
  .github/actions/file-diff/index.js
Labels: skip_vrt

#2362 chore(tokens): move tasks to nx workflow
  .github/actions/file-diff/index.js
  .github/workflows/build.yml
  .github/workflows/publish-site.yml
  package.json
  tasks/compare-compiled-output.js
  tokens/package.json
  tokens/project.json
  yarn.lock
Labels: run_vrt, ready-for-review, high priority

#2363 chore(bundle-builder,component-builder): minor preparations for nx migration
  tools/bundle-builder/lib/depUtils.js
  tools/component-builder/package.json
Labels: size-1 XS, build, run_vrt, ready-for-review

#2364 chore(storybook,ui-icons): clean-up and preparations for nx build
  .storybook/postcss.config.js
  components/assetlist/package.json
  components/dropzone/package.json
  components/icon/stories/icon.stories.js
  components/icon/stories/template.js
  components/icon/stories/utilities.js
  components/miller/package.json
  ui-icons/svgo.config.js
Labels: size-2 S, build, run_vrt, high priority

#2365 chore(ui-icons): publish public access
  ui-icons/package.json
Labels: skip_vrt

#2367 fix(picker): express border width values
  components/picker/themes/express.css
  components/picker/themes/spectrum.css
Labels: run_vrt, ready-to-merge

#2351 docs: storybook wrap, truncate examples part 3
  components/sidenav/stories/sidenav.stories.js
  components/slider/stories/slider.stories.js
  components/statuslight/stories/statuslight.stories.js
  components/statuslight/stories/template.js
  components/switch/stories/switch.stories.js
  components/switch/stories/template.js
  components/tag/stories/tag.stories.js
  components/tag/stories/template.js
  components/tray/stories/template.js
  components/tray/stories/tray.stories.js
Labels: run_vrt, ready-to-merge

#2326 fix(picker): high contrast and other color fixes
  components/picker/index.css
Labels: run_vrt

#2331 docs: storybook wrap and truncate examples part 1
  components/accordion/stories/accordion.stories.js
  components/accordion/stories/template.js
  components/actionbutton/stories/index.js
  components/alertbanner/stories/alertbanner.stories.js
  components/alertbanner/stories/template.js
  components/alertdialog/stories/alertdialog.stories.js
  components/assetlist/stories/assetlist.stories.js
  components/badge/stories/badge.stories.js
  components/badge/stories/template.js
  components/card/stories/card.stories.js
  components/card/stories/template.js
  components/checkbox/stories/checkbox.stories.js
  components/checkbox/stories/template.js
  components/combobox/stories/combobox.stories.js
  components/combobox/stories/template.js
  components/contextualhelp/stories/contextualhelp.stories.js
  components/contextualhelp/stories/template.js
  components/dialog/stories/dialog.stories.js
Labels: run_vrt

#2376 feat(storybook): incorporate the new chromatic plugin
  .env.example
  .gitignore
  .storybook/.env.example
  .storybook/main.js
  .storybook/package.json
  package.json
  tasks/chromatic-config-creation.sh
  tasks/copy-env-from-root.sh
  yarn.lock
Labels: size-1 XS, run_vrt, storybook, ready-for-review
