Repository adobe/spectrum-css, pull requests merged in 2024-11, with the labels that each got.

#3343 chore(storybook): align typography elements for VRTs
  .storybook/decorators/utilities.js
  components/actionbutton/stories/template.js
  components/actiongroup/stories/template.js
  components/alertbanner/stories/template.js
  components/button/stories/template.js
  components/checkbox/stories/template.js
  components/closebutton/stories/template.js
  components/coachindicator/stories/template.js
  components/combobox/stories/template.js
  components/helptext/stories/template.js
  components/menu/stories/template.js
  components/picker/stories/template.js
  components/progressbar/stories/meter.template.js
  components/progressbar/stories/template.js
  components/radio/stories/template.js
  components/search/stories/template.js
  components/statuslight/stories/template.js
  components/steplist/stories/template.js
  components/stepper/stories/template.js
  components/swatch/stories/template.js
  components/swatchgroup/stories/template.js
  components/switch/stories/template.js
  components/tabs/stories/template.js
  components/tag/stories/template.js
  components/textfield/stories/template.js
  components/textfield/stories/textarea.template.js
  components/toast/stories/template.js
  components/tooltip/stories/template.js
  components/typography/stories/template.js
Labels: size-1 XS, skip_vrt, ready-to-merge

#3329 chore(textfield,textarea): add migration guide to changelog
  components/textfield/CHANGELOG.md
Labels: documentation, size-1 XS, skip_vrt, ready-to-merge

#3326 docs(textarea): add corrected guidelines link and rootClass
  components/textfield/stories/textarea.stories.js
  components/textfield/stories/textarea.template.js
Labels: size-1 XS, run_vrt, ready-to-merge, s1

#3372 fix(search): removes calc and replaces w/fixed value
  .changeset/itchy-bikes-join.md
  components/search/index.css
  components/search/metadata/metadata.json
  components/search/metadata/mods.md
Labels: size-3 M, run_vrt, ready-for-review

#3355 feat(avatar): migrate s2 avatar
  .changeset/friendly-dolls-raise.md
  components/avatar/index.css
  components/avatar/stories/avatar.stories.js
Labels: size-3 M, skip_vrt, ready-for-review

#3354 docs: fix and document use of keyboard focus classes on text fields
  components/textfield/stories/template.js
  components/textfield/stories/textarea.stories.js
  components/textfield/stories/textarea.template.js
  components/textfield/stories/textfield.stories.js
Labels: documentation, skip_vrt, ready-for-review

#3328 fix: correct the display of checkbox read-only state
  .changeset/afraid-dogs-worry.md
  .changeset/gold-deers-smash.md
  components/checkbox/index.css
  components/checkbox/metadata/metadata.json
  components/checkbox/stories/checkbox.stories.js
  components/checkbox/stories/checkbox.test.js
  components/checkbox/stories/template.js
  components/fieldgroup/index.css
  components/fieldgroup/metadata/metadata.json
  components/fieldgroup/stories/fieldgroup.mdx
  components/fieldgroup/stories/fieldgroup.stories.js
  components/fieldgroup/stories/template.js
Labels: run_vrt, ready-for-review, s1

#3374 chore(button,link): add more static color tests
  .storybook/decorators/utilities.js
  components/actionbutton/stories/actionbutton.test.js
  components/button/stories/button.test.js
  components/clearbutton/stories/clearbutton.test.js
  components/link/stories/link.test.js
Labels: testing, skip_vrt, ready-for-review

#3350 fix(radio): correct display of read-only state
  .changeset/hot-timers-count.md
  components/fieldgroup/stories/fieldgroup.mdx
  components/fieldgroup/stories/fieldgroup.stories.js
  components/fieldgroup/stories/template.js
  components/radio/index.css
  components/radio/metadata/metadata.json
  components/radio/stories/radio.stories.js
  components/radio/stories/template.js
Labels: size-1 XS, run_vrt, ready-to-merge, s1

#3232 feat(combobox): adding read only state to combobox
  .changeset/new-doors-fold.md
  components/combobox/index.css
  components/combobox/metadata/metadata.json
  components/combobox/metadata/mods.md
  components/combobox/stories/combobox.stories.js
  components/combobox/stories/combobox.test.js
  components/combobox/stories/template.js
Labels: ready-for-review, s1

#3386 chore(storybook): add 404 page
  .storybook/assets/404.html
Labels: size-1 XS, skip_vrt, ready-for-review

#3388 feat(colorarea): S2 migration
  .changeset/spotty-onions-study.md
  components/colorarea/index.css
Labels: size-2 S, skip_vrt, ready-for-review

#3394 feat(thumbnail-opacity-checkboard): S2 migration
  .changeset/twenty-tables-know.md
  components/opacitycheckerboard/index.css
  components/thumbnail/index.css
  components/thumbnail/stories/template.js
Labels: size-2 S, skip_vrt, ready-for-review

#3410 docs: resolve firefox svg clipping for logo on 404 page
  .storybook/assets/404.html
  .storybook/assets/logo.svg
Labels: skip_vrt

#3413 feat: s2 foundations non-gray-800 colors update
  .changeset/weak-kings-pretend.md
  tokens/dist/css/dark-vars.css
  tokens/package.json
  yarn.lock
Labels: run_vrt
