Repository adobe/spectrum-css, pull requests merged in 2024-12, with the labels that each got.

#3431 chore(coachindicator): correct the title of coachindicator
  components/coachindicator/stories/coachindicator.stories.js
Labels: size-1 XS, storybook, ready-for-review, S2

#2860 feat(dialog): s2 standard dialog migration
  .changeset/few-doors-smile.md
  .changeset/loud-vans-brush.md
  .changeset/metal-fireants-switch.md
  components/buttongroup/index.css
  components/buttongroup/metadata/mods.md
  components/dialog/index.css
  components/dialog/metadata/mods.md
  components/dialog/package.json
  components/dialog/stories/dialog.stories.js
  components/dialog/stories/dialog.test.js
  components/dialog/stories/template.js
  components/modal/index.css
  components/modal/stories/template.js
  components/tray/stories/tray.stories.js
  components/underlay/index.css
  tokens/custom/large-vars.css
  tokens/custom/medium-vars.css
  tokens/dist/css/large-vars.css
  tokens/dist/css/medium-vars.css
  tokens/dist/index.css
  yarn.lock
Labels: skip_vrt, ready-to-merge, S2

#3441 fix(swatch): support gradient input
  .changeset/seven-dogs-help.md
  .storybook/decorators/utilities.js
  components/alertbanner/stories/alertbanner.test.js
  components/buttongroup/stories/buttongroup.stories.js
  components/picker/stories/picker.stories.js
  components/picker/stories/picker.test.js
  components/swatch/index.css
  components/swatch/stories/swatch.stories.js
  components/swatch/stories/swatch.test.js
  components/swatch/stories/template.js
  components/tabs/stories/tabs.test.js
Labels: bug, size-2 S, run_vrt, ready-for-review, s1

#3407 chore(accordion,actionbar,asset): remove mdx files
  components/accordion/stories/accordion.mdx
  components/accordion/stories/accordion.stories.js
  components/actionbar/stories/actionbar.mdx
  components/actionbar/stories/actionbar.stories.js
  components/actionbar/stories/template.js
  components/asset/stories/asset.mdx
  components/asset/stories/asset.stories.js
Labels: documentation, size-1 XS, skip_vrt, ready-for-review, low priority, s1

#3454 fix(icon): fix for icons not loading
  components/icon/stories/template.js
Labels: ready-for-review

#2652 feat(alertbanner): migrate to spectrum 2
  .changeset/tame-bobcats-beam.md
  components/alertbanner/index.css
  components/alertbanner/metadata/mods.md
  components/alertbanner/stories/alertbanner.stories.js
  components/alertbanner/stories/template.js
Labels: size-3 M, ready-for-review, S2

#3456 chore(tokens): use spectrum-tokens@13.0.0-beta.55
  .changeset/early-actors-buy.md
  tokens/dist/css/global-vars.css
  tokens/dist/css/large-vars.css
  tokens/dist/css/medium-vars.css
  tokens/dist/index.css
  tokens/package.json
  yarn.lock
Labels: size-1 XS, skip_vrt, ready-for-review

#3409 chore(colorarea,colorhandle,colorloupe,colorslider,colorwheel): remove mdx files
  components/colorarea/stories/colorarea.mdx
  components/colorarea/stories/colorarea.stories.js
  components/colorhandle/stories/colorhandle.mdx
  components/colorhandle/stories/colorhandle.stories.js
  components/colorloupe/stories/colorloupe.mdx
  components/colorloupe/stories/colorloupe.stories.js
  components/colorslider/stories/colorslider.mdx
  components/colorslider/stories/colorslider.stories.js
  components/colorwheel/stories/colorwheel.mdx
  components/colorwheel/stories/colorwheel.stories.js
Labels: documentation, size-1 XS, skip_vrt, ready-for-review, low priority, s1

#3408 chore(assetcard,avatar,badge): remove mdx files
  components/assetcard/stories/assetcard.mdx
  components/assetcard/stories/assetcard.stories.js
  components/avatar/stories/avatar.mdx
  components/avatar/stories/avatar.stories.js
  components/avatar/stories/avatar.test.js
  components/badge/stories/badge.mdx
  components/badge/stories/badge.stories.js
  components/badge/stories/badge.test.js
  components/badge/stories/template.js
Labels: documentation, size-1 XS, skip_vrt, ready-to-merge, low priority, s1

#3443 chore(calendar,card,coachmark): remove MDX files
  components/asset/stories/template.js
  components/calendar/stories/calendar.mdx
  components/calendar/stories/calendar.stories.js
  components/calendar/stories/template.js
  components/card/stories/card.mdx
  components/card/stories/card.stories.js
  components/card/stories/card.test.js
  components/card/stories/template.js
  components/coachmark/stories/coachmark.mdx
  components/coachmark/stories/coachmark.stories.js
  components/coachmark/stories/coachmark.test.js
  components/coachmark/stories/template.js
Labels: documentation, size-1 XS, ready-for-review, low priority, s1
