Repository adobe/spectrum-css, pull requests merged in 2024-03, with the labels that each got.

#2579 fix(menu): disabled color for value text and add disabled stories
  components/menu/index.css
  components/menu/stories/menu.stories.js
  components/menu/stories/template.js
Labels: run_vrt

#2577 chore: minor accordion story updates
  .storybook/DocumentationTemplate.mdx
  components/accordion/stories/accordion.stories.js
  components/accordion/stories/template.js
Labels: documentation, size-1 XS, run_vrt

#2561 refactor(site): tokens system
  components/site/component.css
  components/site/gulpfile.js
  components/site/index.css
  components/site/package.json
  components/site/site.css
Labels: skip_vrt

#2581 build: move postcss reporting to stylelint
  package.json
  plugins/postcss-dropdupedvars/CHANGELOG.md
  plugins/postcss-dropdupedvars/README.md
  plugins/postcss-dropdupedvars/expected/dupes.css
  plugins/postcss-dropdupedvars/fixtures/dupes.css
  plugins/postcss-dropdupedvars/index.js
  plugins/postcss-dropdupedvars/package.json
  plugins/postcss-dropdupedvars/test.js
  plugins/postcss-dropunusedvars/CHANGELOG.md
  plugins/postcss-dropunusedvars/README.md
  plugins/postcss-dropunusedvars/expected/unused.css
  plugins/postcss-dropunusedvars/expected/varRefs.css
  plugins/postcss-dropunusedvars/fixtures/unused.css
  plugins/postcss-dropunusedvars/fixtures/varRefs.css
  plugins/postcss-dropunusedvars/index.js
  plugins/postcss-dropunusedvars/package.json
  plugins/postcss-dropunusedvars/test.js
  stylelint.config.js
  tools/component-builder-simple/css/processors.js
  tools/component-builder-simple/package.json
  yarn.lock
Labels: size-2 S, build, skip_vrt

#2424 docs(tabs): improvements to storybook for tabs
  components/picker/stories/template.js
  components/tabs/stories/index.js
  components/tabs/stories/tabs-horizontal-compact.stories.js
  components/tabs/stories/tabs-horizontal-emphasized.stories.js
  components/tabs/stories/tabs-horizontal-quiet.stories.js
  components/tabs/stories/tabs-horizontal.stories.js
  components/tabs/stories/tabs-vertical-compact.stories.js
  components/tabs/stories/tabs-vertical-emphasized.stories.js
  components/tabs/stories/tabs-vertical-quiet.stories.js
  components/tabs/stories/tabs-vertical.stories.js
  components/tabs/stories/tabs.stories.js
  components/tabs/stories/template.js
Labels: run_vrt

#2564 feat(closebutton)!: migrate to S2
  components/closebutton/index.css
  components/closebutton/metadata/closebutton.yml
  components/closebutton/metadata/mods.md
  components/closebutton/package.json
  components/closebutton/stories/closebutton.stories.js
  components/closebutton/stories/template.js
  components/closebutton/themes/express.css
  components/closebutton/themes/spectrum.css
Labels: wip, run_vrt, S2

#2580 fix(commons): remove renamed mods marked for deprecation
  components/actionbutton/metadata/actionbutton.yml
  components/actionbutton/metadata/mods.md
  components/button/metadata/button-accent.yml
  components/button/metadata/button-negative.yml
  components/button/metadata/button-primary.yml
  components/button/metadata/button-secondary.yml
  components/button/metadata/button-staticcolor.yml
  components/button/metadata/mods.md
  components/closebutton/metadata/closebutton.yml
  components/closebutton/metadata/mods.md
  components/commons/basebutton.css
  components/logicbutton/metadata/logicbutton.yml
  components/logicbutton/metadata/mods.md
  components/picker/metadata/mods.md
  components/picker/metadata/picker.yml
Labels: S2

#2569 feat(fieldlabel)!: s2 migration
  components/fieldlabel/index.css
  components/fieldlabel/metadata/fieldlabel.yml
  components/fieldlabel/metadata/form.yml
  components/fieldlabel/metadata/mods.md
  components/fieldlabel/package.json
  components/fieldlabel/stories/fieldlabel.stories.js
  components/fieldlabel/stories/template.js
Labels: S2

#2592 ci: revert faulty version of reviewdog action
  .github/workflows/lint.yml
Labels: skip_vrt

#2570 fix(button): pending state width, transition
  components/button/index.css
  components/button/metadata/button-pending.yml
  components/button/stories/button.stories.js
  components/button/stories/template.js
  components/progresscircle/index.css
  components/progresscircle/metadata/mods.md
Labels: skip_vrt

#2567 fix(picker): spinner position in RTL direction
  components/picker/index.css
  components/picker/metadata/mods.md
Labels: skip_vrt

#2602 docs(button): fix appearance of pending in forced colors story
  components/button/stories/template.js
Labels: ready-to-merge

#2612 chore(accordion, actionbar, actionbutton, actiongroup): apply minor linting fixes
  components/accordion/index.css
  components/actionbar/index.css
  components/actionbutton/stories/template.js
  components/actiongroup/stories/template.js
Labels: run_vrt

#2611 docs: deprecation pages and styles fixed
  .github/workflows/publish-site.yml
  .storybook/deprecated/splitbutton/splitbutton.yml
  .storybook/package.json
  .storybook/project.json
  components/card/package.json
  components/site/component.css
  package.json
  site/README.md
  site/get-started.pug
  site/halo-focus.pug
  site/includes/dependencies.pug
  site/includes/nav.pug
  site/includes/siteComponent.pug
  site/index.pug
  site/package.json
  site/resources/css/docs.css
  site/resources/css/site.css
  site/resources/js/Search.js
  site/resources/js/SpectrumSwitcher.js
  site/resources/js/adobe-globalnav.js
  site/resources/js/docs.js
  site/resources/js/enhancement.js
  site/resources/js/polyfills.js
  site/resources/js/site.js
  site/resources/js/typekit.js
  site/tasks/builder.js
  site/tasks/server.js
  site/tasks/utilities.js
  site/templates/halo-focus.pug
  site/templates/individualComponent.pug
  site/truncation.pug
  site/util.js
  site/wrapping.pug
  yarn.lock
Labels: documentation, skip_vrt

#2559 feat(cornerrounding): add custom token and foundations documentation
  .storybook/foundations/corner-rounding/action-button-corner-rounding.stories.js
  .storybook/foundations/corner-rounding/checkbox-corner-rounding.stories.js
  .storybook/foundations/corner-rounding/component-size-tokens-medium.md
  .storybook/foundations/corner-rounding/component-size-tokens-small.md
  .storybook/foundations/corner-rounding/corner-rounding.mdx
  .storybook/foundations/corner-rounding/corner-rounding.stories.js
  .storybook/foundations/corner-rounding/index.css
  .storybook/foundations/corner-rounding/template.js
  components/actionbutton/index.css
  components/checkbox/index.css
  components/closebutton/index.css
Labels: ready-for-review, S2

#2613 chore(alertbanner, alertdialog, asset, assetcard): lint fixes
  components/alertbanner/index.css
  components/alertbanner/stories/template.js
  components/alertdialog/stories/template.js
  components/asset/stories/template.js
  components/assetcard/index.css
  components/assetcard/stories/template.js
  components/assetcard/themes/express.css
  components/assetcard/themes/spectrum.css
Labels: run_vrt

#2578 chore: vrt enhancements for button & actionbutton
  .storybook/decorators/contextsWrapper.js
  .storybook/main.js
  .storybook/manager.js
  .storybook/package.json
  .storybook/preview.js
  components/actionbutton/stories/actionbutton-quiet.stories.js
  components/actionbutton/stories/actionbutton-staticblack.stories.js
  components/actionbutton/stories/actionbutton-staticwhite.stories.js
  components/actionbutton/stories/actionbutton.stories.js
  components/actionbutton/stories/index.js
  components/actionbutton/stories/template.js
  components/button/stories/button.stories.js
  components/button/stories/template.js
  components/progresscircle/stories/template.js
  components/typography/stories/template.js
  postcss.config.js
  yarn.lock
Labels: testing, size-2 S, run_vrt, ready-for-review
