Repository adobe/spectrum-css, pull requests merged in 2024-08, with the labels that each got.

#2960 chore(storybook): move token loader into own file
  .storybook/loaders/index.js
  .storybook/loaders/token-loader.js
  .storybook/preview.js
Labels: size-1 XS, run_vrt, storybook, ready-for-review

#2963 docs: clarify usage of very low opacity on some inputs
  components/checkbox/index.css
  components/dial/index.css
  components/slider/index.css
Labels: documentation, size-1 XS, ready-to-merge, low priority

#2973 chore: fix stylelint extension error
  .github/workflows/lint.yml
  nx.json
Labels: size-2 S, skip_vrt, high priority

#2954 feat(swatch): add support for lightBorder
  .changeset/pretty-socks-notice.md
  components/swatch/index.css
  components/swatch/metadata/mods.md
Labels: size-1 XS, ready-to-merge

#2961 fix(breadcrumb): center breadcrumb itemLink
  .changeset/gold-spies-learn.md
  components/breadcrumb/index.css
Labels: size-1 XS, run_vrt, ready-for-review

#2943 docs(taggroup, thumbnail, tray, treeview, well): docs site to storybook
  components/taggroup/CHANGELOG.md
  components/taggroup/stories/taggroup.stories.js
  components/taggroup/stories/template.js
  components/thumbnail/CHANGELOG.md
  components/thumbnail/stories/template.js
  components/thumbnail/stories/thumbnail.stories.js
  components/tray/stories/tray.stories.js
  components/treeview/CHANGELOG.md
  components/treeview/stories/template.js
  components/treeview/stories/treeview.stories.js
  components/well/stories/well.stories.js
Labels: documentation, skip_vrt, storybook, ready-for-review

#2974 fix(icon): remove legacy ie overflow css causing ios clipping issues
  .changeset/lucky-dots-live.md
  components/icon/icons.css
Labels: size-1 XS, run_vrt, ready-for-review

#2965 fix: static white meter story and corrected fill colors
  .changeset/lucky-jeans-happen.md
  components/progressbar/index.css
  components/progressbar/stories/meter.stories.js
Labels: size-2 S, run_vrt, storybook, ready-to-merge

#2955 fix(card)!: change cover photo background color and include mod
  .changeset/little-dodos-peel.md
  components/card/index.css
Labels: size-1 XS, do not merge, run_vrt, ready-for-review

#2854 docs(modal,pagination,pickerbutton): site docs to storybook
  components/modal/stories/modal.stories.js
  components/modal/stories/template.js
  components/pagination/stories/pagination.stories.js
  components/pagination/stories/template.js
  components/pickerbutton/CHANGELOG.md
  components/pickerbutton/stories/pickerbutton.stories.js
  components/pickerbutton/stories/template.js
Labels: documentation, run_vrt, storybook, ready-for-review

#2929 fix(progressbar): revert background-color to background
  .changeset/bright-zoos-grab.md
  components/progressbar/index.css
  components/progressbar/stories/meter.test.js
  components/progressbar/stories/progressbar.stories.js
  components/progressbar/stories/progressbar.test.js
  components/progressbar/stories/template.js
Labels: run_vrt, ready-for-review

#2793 docs(breadcrumb, checkbox, clearbutton, coachindicator): Site Docs to Storybook
  .storybook/decorators/utilities.js
  .storybook/guides/develop.mdx
  components/breadcrumb/stories/breadcrumb.stories.js
  components/breadcrumb/stories/breadcrumb.test.js
  components/breadcrumb/stories/template.js
  components/checkbox/stories/checkbox.stories.js
  components/checkbox/stories/checkbox.test.js
  components/checkbox/stories/template.js
  components/clearbutton/stories/clearbutton.stories.js
  components/clearbutton/stories/clearbutton.test.js
  components/clearbutton/stories/template.js
  components/coachindicator/stories/coachindicator.stories.js
  components/coachindicator/stories/template.js
Labels: documentation, size-2 S, ready-for-review

#2833 docs(dial,dialog,divider,dropindicator): Migrate docs to storybook pt7
  components/dial/stories/dial.stories.js
  components/dial/stories/dial.test.js
  components/dial/stories/template.js
  components/dialog/stories/dialog.stories.js
  components/dialog/stories/dialog.test.js
  components/dialog/stories/template.js
  components/divider/stories/divider.stories.js
  components/divider/stories/divider.test.js
  components/divider/stories/template.js
  components/dropindicator/stories/dropindicator.stories.js
  components/dropindicator/stories/template.js
  components/tray/stories/tray.stories.js
  components/tray/stories/tray.test.js
Labels: documentation, run_vrt, storybook, ready-for-review, high priority

#2884 docs(inlinealert,link,logicbutton,miller): docs migration from static site to storybook
  components/inlinealert/stories/inlinealert.stories.js
  components/inlinealert/stories/inlinealert.test.js
  components/inlinealert/stories/template.js
  components/link/CHANGELOG.md
  components/link/stories/link.stories.js
  components/link/stories/template.js
  components/logicbutton/stories/logicbutton.stories.js
  components/logicbutton/stories/template.js
  components/miller/stories/miller.stories.js
Labels: documentation, run_vrt, storybook, ready-for-review

#2900 docs(slider,stepper,steplist): docs from static site to storybook
  components/slider/CHANGELOG.md
  components/slider/stories/slider.stories.js
  components/slider/stories/slider.test.js
  components/slider/stories/template.js
  components/steplist/stories/steplist.stories.js
  components/steplist/stories/steplist.test.js
  components/steplist/stories/template.js
  components/stepper/CHANGELOG.md
  components/stepper/stories/stepper.stories.js
  components/stepper/stories/template.js
Labels: documentation, run_vrt, storybook, ready-for-review

#3020 chore: set lint action to review PR not just check
  .github/workflows/lint.yml
Labels: size-1 XS, build, skip_vrt, ready-for-review, low priority

#3032 chore: expand reviewers for dependabot
  .github/dependabot.yml
Labels: size-1 XS, skip_vrt, ready-for-review, low priority

#3023 fix(progressbar, search, pickerbutton): migrate --mod variables to index.css
  .changeset/heavy-teachers-drop.md
  components/pickerbutton/index.css
  components/pickerbutton/metadata/metadata.json
  components/pickerbutton/themes/spectrum-two.css
  components/progressbar/index.css
  components/progressbar/metadata/metadata.json
  components/progressbar/themes/spectrum-two.css
  components/search/index.css
  components/search/metadata/metadata.json
  components/search/metadata/mods.md
  components/search/themes/spectrum-two.css
  tokens/components/bridge/pickerbutton.css
  tokens/components/bridge/progressbar.css
  tokens/components/bridge/search.css
  tokens/components/express/pickerbutton.css
  tokens/components/express/progressbar.css
  tokens/components/express/search.css
  tokens/components/spectrum-two/pickerbutton.css
  tokens/components/spectrum-two/progressbar.css
  tokens/components/spectrum-two/search.css
  tokens/components/spectrum/pickerbutton.css
  tokens/components/spectrum/progressbar.css
  tokens/components/spectrum/search.css
Labels: ready-for-review

#2984 chore: color docs for storybook
  .storybook/blocks/ColorPalette.jsx
  .storybook/blocks/ComponentDetails.jsx
  .storybook/blocks/ThemeContainer.jsx
  .storybook/blocks/Typography.jsx
  .storybook/blocks/component-details.css
  .storybook/blocks/component-details.jsx
  .storybook/blocks/index.js
  .storybook/blocks/utilities.js
  .storybook/guides/color_palette.mdx
  .storybook/manager.js
Labels: documentation, skip_vrt, storybook, ready-for-review, low priority

#2980 fix(menu): do not rely on source order of icon dependency css
  .changeset/chatty-jokes-chew.md
  components/menu/index.css
  components/menu/metadata/metadata.json
Labels: run_vrt, ready-for-review

#3036 fix(treeview, tabs, combobox): migrate --mods to index.css
  .changeset/fuzzy-brooms-jam.md
  .changeset/fuzzy-jokes-begin.md
  components/combobox/index.css
  components/combobox/themes/spectrum-two.css
  components/tabs/index.css
  components/tabs/themes/spectrum-two.css
  components/treeview/index.css
  components/treeview/themes/spectrum-two.css
  tokens/custom/dark-vars.css
  tokens/custom/light-vars.css
  tokens/dist/css/dark-vars.css
  tokens/dist/css/light-vars.css
  tokens/dist/index.css
Labels: ready-for-review

#3043 build: postcss formatting updates
  postcss.config.js
Labels: size-2 S, build, run_vrt, ready-for-review
