Repository adobe/spectrum-css, pull requests merged in 2024-02, with the labels that each got.

#2491 docs: storybook updates for icon sets, arrow and chevron
  components/actionbutton/stories/template.js
  components/combobox/stories/template.js
  components/pagination/stories/template.js
  components/picker/stories/template.js
  components/pickerbutton/stories/template.js
  components/treeview/stories/template.js
Labels: run_vrt

#2439 build: remove postcss-logical plugin
  components/splitbutton/index.css
  tools/component-builder/css/processors.js
  tools/component-builder/package.json
  yarn.lock
Labels: run_vrt, ready-for-review

#2483 fix(coachindicator): address issues with coach indicator rings position
  components/coachindicator/index.css
  components/coachindicator/metadata/coachindicator.yml
  components/coachindicator/metadata/mods.md
  components/coachindicator/stories/coachindicator.stories.js
Labels: ready-to-merge

#2458 docs(accordion): addresses issue with disabled state in storybook
  components/accordion/stories/accordion.stories.js
  components/accordion/stories/template.js
Labels: run_vrt, ready-to-merge

#2496 chore(tokens): inconsistent compilation results caused by caching
  tokens/project.json
Labels: skip_vrt, ready-for-review

#2492 fix(component-builder): remove unused postcss-svg plugin
  tools/component-builder/css/processors.js
  tools/component-builder/package.json
  yarn.lock
Labels: size-1 XS, run_vrt, ready-to-merge

#2498 ci(actions): bump to v4, resolve outdated node messages
  .github/workflows/build.yml
  .github/workflows/compare-results.yml
  .github/workflows/lint.yml
  .github/workflows/publish-site.yml
  .github/workflows/vrt.yml
Labels: skip_vrt, ready-for-review

#2481 docs(combobox): increase chromatic coverage of variants
  components/combobox/stories/combobox.stories.js
  components/combobox/stories/template.js
Labels: ready-for-review

#2499 chore(storybook): allow local preview of chromatic snapshots
  .storybook/README.md
  .storybook/decorators/contextsWrapper.js
  .storybook/decorators/index.js
  .storybook/decorators/withTestingPreviewWrapper.js
  .storybook/preview.js
  components/accordion/stories/accordion.stories.js
  components/alertbanner/stories/alertbanner.stories.js
  components/calendar/stories/calendar.stories.js
  components/calendar/stories/template.js
  components/coachindicator/stories/coachindicator.stories.js
  components/dropzone/stories/dropzone.stories.js
  components/icon/stories/icon.stories.js
  components/illustratedmessage/stories/illustratedmessage.stories.js
  components/inlinealert/stories/inlinealert.stories.js
  components/statuslight/stories/statuslight.stories.js
  components/stepper/stories/stepper.stories.js
  components/tray/stories/tray.stories.js
Labels: enhancement, wip, run_vrt

#2477 docs(textarea): example text is more relevant to component
  components/textfield/metadata/textarea.yml
  components/textfield/metadata/textfield.yml
Labels: skip_vrt, ready-for-review

#1680 feat(preview): add figma support to storybook [CSS-284]
  .storybook/main.js
  components/actionbar/stories/actionbar.stories.js
  generator/templates/stories/{{ folderName }}.stories.js.hbs
Labels: enhancement, skip_vrt, ready-for-review

#2465 fix(picker): quiet side label picker positioning
  components/fieldlabel/index.css
  components/fieldlabel/metadata/mods.md
  components/fieldlabel/stories/form-template.js
  components/picker/index.css
  components/picker/stories/picker.stories.js
  components/picker/stories/template.js
Labels: ready-for-review

#2515 chore(calendar): correct fallback date for testing
  .storybook/decorators/withTestingPreviewWrapper.js
  .storybook/preview.js
  components/calendar/stories/calendar.stories.js
  components/calendar/stories/template.js
Labels: run_vrt, ready-for-review, high priority

#2325 fix(slider): high contrast improvements for filled track
  components/slider/index.css
Labels: run_vrt, ready-for-review

#2455 ci: separate build matrix from workflow
  .github/workflows/build.yml
  .github/workflows/compare-results.yml
  .github/workflows/development.yml
  .github/workflows/production.yml
Labels: skip_vrt, ready-for-review

#2516 ci: allow skip_vrt to build preview site
  .github/workflows/development.yml
Labels: skip_vrt, ready-for-review

#2501 chore: add documentation resources to storybook
  .storybook/README.md
  .storybook/guides/code_of_conduct.mdx
  .storybook/guides/develop.mdx
  .storybook/main.js
  .storybook/preview.js
  assets/spectrum-css_illustration_desktop.png
  assets/spectrum_illustration_2x.png
Labels: size-2 S, skip_vrt

#2304 refactor(quickaction): deprecate component; support this in docs
  .storybook/deprecated/quickaction/quickaction.stories.js
  .storybook/deprecated/quickaction/quickaction.yml
  .storybook/main.js
  .storybook/package.json
  README.md
  components/card/stories/card.stories.js
  components/quickaction/CHANGELOG.md
  components/quickaction/README.md
  components/quickaction/gulpfile.js
  components/quickaction/index.css
  components/quickaction/metadata/mods.md
  components/quickaction/package.json
  components/quickaction/project.json
  components/quickaction/stories/template.js
  site/templates/siteComponent.pug
  tasks/clean-up-after-migration.sh
  tools/bundle-builder/dev/index.js
  tools/bundle-builder/docs/index.js
  tools/bundle-builder/index.js
  tools/bundle-builder/lib/depUtils.js
  tools/bundle-builder/package.json
  tools/bundle-builder/subrunner/index.js
  tools/component-builder/docs/index.js
  yarn.lock
Labels: run_vrt, ready-for-review, high priority

#2502 docs(combobox): update to use local chromatic preview
  components/combobox/stories/combobox.stories.js
Labels: ready-to-merge

#2522 docs(storybook): deprecation workflow
  .storybook/guides/deprecation.mdx
  .storybook/package.json
  README.md
Labels: documentation, skip_vrt, ready-for-review

#2530 chore(docs): increase dark mode compatibility
  .storybook/deprecated/quickaction/quickaction.yml
  components/accordion/metadata/accordion.yml
  components/actionbar/metadata/actionbar.yml
  components/actionbutton/metadata/actionbutton.yml
  components/actiongroup/metadata/actiongroup.yml
  components/avatar/metadata/avatar.yml
  components/badge/metadata/badge.yml
  components/breadcrumb/metadata/breadcrumb.yml
  components/button/metadata/button-accent.yml
  components/button/metadata/button-negative.yml
  components/button/metadata/button-primary.yml
  components/button/metadata/button-secondary.yml
  components/button/metadata/button-staticcolor.yml
  components/buttongroup/metadata/buttongroup.yml
  components/checkbox/metadata/checkbox.yml
  components/closebutton/metadata/closebutton.yml
  components/colorarea/metadata/colorarea.yml
  components/colorslider/metadata/colorslider.yml
  components/colorwheel/metadata/colorwheel.yml
  components/contextualhelp/metadata/contextualhelp.yml
  components/divider/metadata/divider.yml
  components/fieldlabel/metadata/fieldlabel.yml
  components/floatingactionbutton/metadata/floatingactionbutton.yml
  components/helptext/metadata/helptext.yml
  components/inlinealert/metadata/inlinealert.yml
  components/link/metadata/link.yml
  components/menu/metadata/menu.yml
  components/modal/metadata/modal.yml
  components/picker/metadata/picker.yml
  components/popover/metadata/popover.yml
  components/progressbar/metadata/meter.yml
  components/progresscircle/metadata/progresscircle.yml
  components/radio/metadata/radio.yml
  components/statuslight/metadata/statuslight.yml
  components/swatch/metadata/swatch.yml
  components/swatchgroup/metadata/swatchgroup.yml
  components/switch/metadata/switch.yml
  components/table/metadata/table.yml
  components/tag/metadata/tag.yml
  components/taggroup/metadata/taggroup.yml
  components/toast/metadata/toast.yml
  components/tooltip/metadata/tooltip.yml
  components/tray/metadata/tray.yml
  components/treeview/metadata/treeview.yml
  components/typography/metadata/typography.yml
  site/templates/siteComponent.pug
Labels: documentation, skip_vrt, ready-for-review

#2503 docs: readme - clarify browser support and remove ie11 broken link
  README.md
Labels: skip_vrt, ready-to-merge

#2527 refactor(splitbutton): deprecate component
  .storybook/deprecated/splitbutton/splitbutton.stories.js
  .storybook/deprecated/splitbutton/splitbutton.yml
  .storybook/postcss.config.js
  components/splitbutton/CHANGELOG.md
  components/splitbutton/README.md
  components/splitbutton/gulpfile.js
  components/splitbutton/index.css
  components/splitbutton/package.json
  components/splitbutton/project.json
  components/splitbutton/stories/template.js
  package.json
  tasks/clean-up-after-migration.sh
  yarn.lock
Labels: ready-for-review

#2529 chore(searchwithin): setup for deprecation
  components/searchwithin/metadata/searchwithin.yml
  components/searchwithin/stories/searchwithin.stories.js
Labels: skip_vrt, ready-to-merge, deprecation

#2536 docs(cyclebutton): setup for deprecation
  .storybook/guides/deprecation.mdx
  components/cyclebutton/metadata/cyclebutton.yml
  components/cyclebutton/stories/cyclebutton.stories.js
Labels: ready-for-review

#2519 fix(textfield): remove extra padding on nested label and help
  components/textfield/index.css
  components/textfield/stories/template.js
Labels: run_vrt

#2248 fix(button): support for wrapping text
  components/button/index.css
  components/button/metadata/mods.md
  components/button/package.json
  components/button/stories/button.stories.js
Labels: run_vrt, ready-to-merge

#2547 fix(tray): full width at portrait orientation
  components/tray/index.css
  components/tray/metadata/mods.md
  components/tray/metadata/tray.yml
  components/tray/stories/template.js
  components/tray/stories/tray.stories.js
Labels: run_vrt

#2551 chore: update clean-up script for more flexible removals
  tasks/clean-up-after-migration.sh
Labels: skip_vrt, ready-for-review

#2537 refactor(searchwithin): deprecate component
  .storybook/deprecated/searchwithin/searchwithin.stories.js
  .storybook/deprecated/searchwithin/searchwithin.yml
  components/searchwithin/CHANGELOG.md
  components/searchwithin/README.md
  components/searchwithin/gulpfile.js
  components/searchwithin/index.css
  components/searchwithin/package.json
  components/searchwithin/project.json
  components/searchwithin/stories/template.js
  package.json
  tools/bundle-builder/dev/index.js
  tools/bundle-builder/docs/index.js
  tools/bundle-builder/lib/depUtils.js
  yarn.lock
Labels: skip_vrt, ready-to-merge

#2553 refactor(asset): migrate to tokens package
  components/asset/gulpfile.js
  components/asset/index.css
  components/asset/metadata/mods.md
  components/asset/package.json
  components/asset/stories/asset.stories.js
Labels: run_vrt, diy-token-migration, ready-to-merge

#2565 ci: remove spectrum-two from automated VRT runs
  .github/workflows/development.yml
  .github/workflows/production.yml
Labels: skip_vrt, ready-for-review
