Repository adobe/spectrum-css, pull requests merged in 2024-10, with the labels that each got.

#3102 docs(actionbutton): migrate docs to storybook
  components/actionbutton/CHANGELOG.md
  components/actionbutton/metadata/actionbutton.yml
  components/actionbutton/stories/actionbutton.stories.js
  components/actionbutton/stories/actionbutton.test.js
  components/actionbutton/stories/template.js
Labels: run_vrt, storybook, ready-for-review, s1

#3174 docs(search): storybook doc migrations
  components/search/stories/search.stories.js
  components/search/stories/template.js
Labels: storybook, ready-for-review, s1

#3126 docs(tags): migrate docs to storybook
  components/tag/index.css
  components/tag/stories/tag.stories.js
  components/tag/stories/template.js
Labels: storybook, ready-for-review, s1

#3152 docs(statuslight): docs to storybook migration
  components/statuslight/CHANGELOG.md
  components/statuslight/stories/statuslight.stories.js
  components/statuslight/stories/statuslight.test.js
  components/statuslight/stories/template.js
Labels: documentation, size-1 XS, run_vrt, ready-for-review, s1

#3190 chore: make postcss-splitinator pkg private
  plugins/postcss-splitinator/package.json
Labels: skip_vrt

#3154 fix(slider ramp): correct handle and ramp vertical alignment
  .changeset/rude-rivers-crash.md
  components/slider/index.css
  components/slider/metadata/metadata.json
Labels: skip_vrt, ready-for-review

#3165 docs(fieldlabel/form): migrates docs to storybook
  components/fieldlabel/stories/fieldlabel.stories.js
  components/fieldlabel/stories/fieldlabel.test.js
  components/fieldlabel/stories/form.stories.js
  components/fieldlabel/stories/form.template.js
  components/fieldlabel/stories/form.test.js
Labels: documentation, size-1 XS, skip_vrt, ready-to-merge, s1

#3164 fix: blank field group docs and read-only radio alignment
  .changeset/three-months-provide.md
  components/fieldgroup/stories/fieldgroup.stories.js
  components/radio/index.css
Labels: skip_vrt, ready-for-review

#3197 fix(button): use appropriate tokens for radii in buttons
  .changeset/soft-ways-drop.md
  components/button/index.css
  components/button/metadata/metadata.json
Labels: run_vrt, ready-for-review

#3189 docs(underlay): migrate docs to storybook
  components/underlay/stories/underlay.stories.js
Labels: size-1 XS, skip_vrt, storybook, ready-for-review, s1

#3210 chore: corrects readOnly to isReadOnly arg
  components/datepicker/stories/datepicker.test.js
Labels: size-1 XS, run_vrt, s1

#3202 docs: add links to figma assets part 1
  components/accordion/stories/accordion.stories.js
  components/actionbar/stories/actionbar.stories.js
  components/actionbutton/stories/actionbutton.stories.js
  components/actiongroup/stories/actiongroup.stories.js
  components/alertbanner/stories/alertbanner.stories.js
  components/alertdialog/stories/alertdialog.stories.js
  components/avatar/stories/avatar.stories.js
  components/badge/stories/badge.stories.js
  components/breadcrumb/stories/breadcrumb.stories.js
  components/button/stories/button.stories.js
  components/buttongroup/stories/buttongroup.stories.js
Labels: size-1 XS, skip_vrt, ready-for-review, S2

#3175 docs(switch): docs site to storybook
  components/switch/CHANGELOG.md
  components/switch/stories/switch.stories.js
  components/switch/stories/switch.test.js
  components/switch/stories/template.js
Labels: skip_vrt, storybook, ready-for-review, s1

#3216 ci: refine branch pointers for selective VRT
  .github/workflows/vrt.yml
  nx.json
Labels: skip_vrt

#3203 docs: add links to figma assets part 2
  components/checkbox/stories/checkbox.stories.js
  components/closebutton/stories/closebutton.stories.js
  components/coachindicator/stories/coachindicator.stories.js
  components/coachmark/stories/coachmark.stories.js
  components/colorarea/stories/colorarea.stories.js
  components/colorhandle/stories/colorhandle.stories.js
  components/colorslider/stories/colorslider.stories.js
  components/colorwheel/stories/colorwheel.stories.js
  components/combobox/stories/combobox.stories.js
  components/contextualhelp/stories/contextualhelp.stories.js
Labels: size-1 XS, skip_vrt, ready-for-review, S2

#3160 docs(actiongroup): migrating docs to storybook
  components/actiongroup/stories/actiongroup.stories.js
  components/actiongroup/stories/actiongroup.test.js
  components/actiongroup/stories/template.js
Labels: storybook, ready-for-review, s1

#3205 docs: add links to figma assets part 3
  components/dialog/stories/dialog.stories.js
  components/divider/stories/divider.stories.js
  components/dropzone/stories/dropzone.stories.js
  components/fieldlabel/stories/fieldlabel.stories.js
  components/helptext/stories/helptext.stories.js
  components/illustratedmessage/stories/illustratedmessage.stories.js
  components/inlinealert/stories/inlinealert.stories.js
  components/link/stories/link.stories.js
  components/menu/stories/menu.stories.js
  components/picker/stories/picker.stories.js
  components/progressbar/stories/meter.stories.js
Labels: size-1 XS, skip_vrt, ready-for-review, S2

#3206 docs: add links to figma assets part 4
  components/popover/stories/popover.stories.js
  components/progressbar/stories/progressbar.stories.js
  components/progresscircle/stories/progresscircle.stories.js
  components/radio/stories/radio.stories.js
  components/rating/stories/rating.stories.js
  components/search/stories/search.stories.js
  components/sidenav/stories/sidenav.stories.js
  components/slider/stories/slider.stories.js
  components/statuslight/stories/statuslight.stories.js
  components/stepper/stories/stepper.stories.js
  components/swatch/stories/swatch.stories.js
  components/swatchgroup/stories/swatchgroup.stories.js
Labels: size-1 XS, skip_vrt, ready-for-review, S2

#3198 chore(typography): add fallback sizes for testing
  components/typography/stories/template.js
Labels: size-1 XS, run_vrt, storybook, ready-to-merge

#3156 docs(toast): migrate docs to storybook
  components/toast/stories/template.js
  components/toast/stories/toast.stories.js
  components/toast/stories/toast.test.js
Labels: run_vrt, s1

#3200 docs(picker): migrate docs to storybook
  components/picker/CHANGELOG.md
  components/picker/stories/picker.stories.js
  components/picker/stories/picker.test.js
  components/picker/stories/template.js
  components/tabs/stories/template.js
Labels: documentation, ready-for-review

#3222 fix(search): addresses quiet variant clear icon positioning
  .changeset/chatty-carrots-warn.md
  components/search/index.css
  components/search/metadata/metadata.json
Labels: skip_vrt, ready-for-review

#3172 chore(storybook): support static color settings in testing grid
  .storybook/assets/base.css
  .storybook/decorators/context.js
  .storybook/decorators/helpers.js
  .storybook/decorators/utilities.js
  components/actionbutton/stories/actionbutton.stories.js
  components/actionbutton/stories/actionbutton.test.js
  components/actionbutton/stories/template.js
  components/actiongroup/stories/actiongroup.test.js
  components/badge/stories/badge.test.js
  components/button/stories/button.stories.js
  components/button/stories/button.test.js
  components/clearbutton/stories/clearbutton.stories.js
  components/clearbutton/stories/clearbutton.test.js
  components/clearbutton/stories/template.js
  components/closebutton/stories/closebutton.test.js
  components/divider/stories/divider.stories.js
  components/divider/stories/divider.test.js
  components/link/stories/link.stories.js
  components/link/stories/link.test.js
  components/progressbar/stories/meter.stories.js
  components/progressbar/stories/meter.test.js
  components/progressbar/stories/progressbar.stories.js
  components/progressbar/stories/progressbar.test.js
  components/progresscircle/stories/progresscircle.stories.js
  components/progresscircle/stories/progresscircle.test.js
Labels: size-5 L, run_vrt, storybook, ready-for-review

#3219 docs(combobox): update placeholder text
  components/combobox/stories/combobox.mdx
  components/combobox/stories/combobox.stories.js
  components/combobox/stories/combobox.test.js
  components/combobox/stories/template.js
Labels: run_vrt, storybook, ready-to-merge

#3220 fix(picker): update picker display and icon flex properties to resolve layout bugs
  .changeset/chatty-sheep-draw.md
  components/picker/index.css
Labels: skip_vrt, ready-for-review

#3230 chore[actionbutton, actiongroup]: fix application of aria-labels
  components/actionbutton/stories/actionbutton.stories.js
  components/actionbutton/stories/template.js
  components/actiongroup/stories/actiongroup.stories.js
  components/actiongroup/stories/template.js
Labels: a11y, size-1 XS, skip_vrt

#3242 chore: update vscode settings and suggestions
  .vscode/extensions.json
  .vscode/settings.json
Labels: size-1 XS, skip_vrt, ready-for-review, low priority, s1

#3227 fix(field-group): addresses regressions in field groups.
  components/fieldgroup/stories/fieldgroup.stories.js
  components/fieldgroup/stories/template.js
Labels: skip_vrt, ready-for-review

#3231 docs(meter): let meter use its rootclass in storybook
  components/progressbar/stories/meter.stories.js
  components/progressbar/stories/meter.template.js
Labels: ready-for-review

#3248 fix(thumbnail): incorrect opacity variable used
  .changeset/green-ants-accept.md
  components/thumbnail/index.css
  components/thumbnail/metadata/metadata.json
Labels: bug, size-1 XS, skip_vrt, ready-to-merge, s1

#3249 chore(typography): fallback sizing for detail at xxs
  components/typography/stories/template.js
Labels: testing, size-1 XS, skip_vrt, storybook, ready-for-review, s1

#3250 fix(closebutton): t-shirt sizing variable fix
  .changeset/funny-jobs-relax.md
  .storybook/decorators/utilities.js
  components/closebutton/index.css
  components/closebutton/metadata/metadata.json
  components/closebutton/stories/closebutton.stories.js
  components/closebutton/stories/closebutton.test.js
Labels: testing, size-1 XS, skip_vrt, storybook, ready-for-review, s1

#3259 chore(field-group): update field group tests
  components/fieldgroup/stories/fieldgroup.test.js
Labels: size-1 XS, run_vrt, ready-for-review, s1

#3264 chore(stylelint-assetlist): adjust declaration order to resolve lint violation
  .changeset/wild-crabs-allow.md
  components/assetlist/index.css
Labels: size-1 XS, skip_vrt, ready-for-review

#3262 chore(stylelint): config updates
  components/clearbutton/index.css
  stylelint.config.js
Labels: size-1 XS, skip_vrt, ready-for-review

#3265 chore(stylelint-badge): create property for forced-colors value to satisfy lint requirements
  .changeset/silver-pianos-develop.md
  components/badge/index.css
  components/badge/metadata/metadata.json
Labels: size-1 XS, skip_vrt, ready-for-review

#3268 fix(actionbutton): static selected actionbutton content colors
  .changeset/smart-worms-pump.md
  components/actionbutton/metadata/metadata.json
  components/actionbutton/themes/spectrum-two.css
  tokens/dist/css/components/bridge/actionbutton.css
  tokens/dist/css/components/bridge/index.css
  tokens/dist/css/components/express/actionbutton.css
  tokens/dist/css/components/express/index.css
  tokens/dist/css/components/spectrum-two/actionbutton.css
  tokens/dist/css/components/spectrum/actionbutton.css
  tokens/dist/css/components/spectrum/index.css
Labels: skip_vrt, S2

#3253 feat(card,contextualhelp,swatch,tokens): add theme tokens for components to global scope
  .changeset/flat-toys-battle.md
  .changeset/forty-radios-type.md
  components/card/index.css
  components/card/metadata/metadata.json
  components/contextualhelp/index.css
  components/contextualhelp/metadata/metadata.json
  components/swatch/index.css
  components/swatch/metadata/metadata.json
  tokens/custom-spectrum/custom-dark-vars.css
  tokens/custom-spectrum/custom-darkest-vars.css
  tokens/custom-spectrum/custom-large-vars.css
  tokens/custom-spectrum/custom-light-vars.css
  tokens/custom-spectrum/custom-medium-vars.css
  tokens/custom-spectrum/custom-vars.css
  tokens/dist/css/spectrum/custom-large-vars.css
  tokens/dist/css/spectrum/custom-medium-vars.css
  tokens/dist/css/spectrum/custom-vars.css
  tokens/dist/css/spectrum/dark-vars.css
  tokens/dist/css/spectrum/darkest-vars.css
  tokens/dist/css/spectrum/global-vars.css
  tokens/dist/css/spectrum/index.css
  tokens/dist/css/spectrum/large-vars.css
  tokens/dist/css/spectrum/light-vars.css
  tokens/dist/css/spectrum/medium-vars.css
  tokens/dist/index.css
Labels: size-3 M, skip_vrt, ready-to-merge, s1

#3270 chore(stylelint): remove stylelint disable comments
  .changeset/serious-pumpkins-share.md
  components/closebutton/index.css
  components/search/index.css
Labels: size-1 XS, skip_vrt, ready-for-review

#3272 chore(stylelint): disable stylelint violation; use comment as description
  .changeset/two-mayflies-divide.md
  components/colorloupe/index.css
Labels: size-1 XS, skip_vrt, ready-for-review

#3273 chore(stylelint): move property declarations + disable violation
  .changeset/quick-paws-lick.md
  components/colorwheel/index.css
Labels: size-1 XS, skip_vrt, ready-for-review

#3286 chore(stylelint): remove custom properties; add todo to description
  .changeset/nine-humans-notice.md
  components/dial/index.css
  components/dial/metadata/metadata.json
Labels: size-1 XS, skip_vrt, ready-for-review

#3266 fix(coachindicator): adds 'static white', deprecates light/dark
  .changeset/cool-kangaroos-flow.md
  components/coachindicator/index.css
  components/coachindicator/metadata/metadata.json
  components/coachindicator/stories/coachindicator.stories.js
  components/coachindicator/stories/coachindicator.test.js
  components/coachindicator/stories/template.js
  tokens/custom-spectrum/custom-vars.css
  tokens/dist/css/spectrum/custom-vars.css
  tokens/dist/css/spectrum/global-vars.css
  tokens/dist/css/spectrum/index.css
  tokens/dist/index.css
Labels: size-1 XS, run_vrt, ready-to-merge, deprecation, s1

#3284 chore(colorslider): remove unused properties
  .changeset/ten-tables-cross.md
  components/colorslider/index.css
  components/colorslider/metadata/metadata.json
Labels: size-1 XS, skip_vrt, ready-for-review

#3289 chore(infieldbutton): remove unused property
  .changeset/ninety-clocks-grin.md
  components/infieldbutton/index.css
  components/infieldbutton/metadata/metadata.json
Labels: size-1 XS, skip_vrt, ready-for-review

#3298 chore(slider): add comment as description to stylelint disable
  .changeset/wet-bulldogs-shake.md
  components/slider/index.css
Labels: size-1 XS, skip_vrt, ready-for-review

#3290 chore(menu): remove unused property
  .changeset/long-geckos-remember.md
  components/menu/index.css
  components/menu/metadata/metadata.json
Labels: size-1 XS, run_vrt, ready-for-review

#3291 chore(progressbar): remove unused property
  .changeset/quiet-dragons-play.md
  components/progressbar/index.css
  components/progressbar/metadata/metadata.json
Labels: size-1 XS, run_vrt, ready-for-review

#3294 chore(rating): create property for forced-colors value to satisfy lint requirements
  .changeset/flat-ads-compete.md
  components/rating/index.css
  components/rating/metadata/metadata.json
Labels: size-1 XS, run_vrt, ready-for-review

#3295 chore(search): move custom property to resolve lint violation
  .changeset/gold-pens-clean.md
  components/search/index.css
Labels: size-1 XS, skip_vrt, ready-for-review

#3299 chore(statuslight): adjust declaration order to resolve lint violations
  .changeset/loud-flies-camp.md
  components/statuslight/index.css
Labels: size-1 XS, skip_vrt, ready-for-review

#3303 chore(stepper): remove unused properties; add comment description
  .changeset/young-turtles-trade.md
  components/stepper/index.css
  components/stepper/metadata/metadata.json
Labels: size-1 XS, run_vrt, ready-for-review

#3307 chore(tag): adjust custom property order to resolve lint violations
  .changeset/hungry-cougars-end.md
  components/tag/index.css
Labels: size-1 XS, run_vrt, ready-for-review

#3300 fix(CSS-1009): stylelint clean-up for unused custom properties
  .changeset/few-icons-kneel.md
  .changeset/khaki-pugs-rescue.md
  .changeset/wise-apricots-repeat.md
  components/colorslider/index.css
  components/datepicker/index.css
  components/dropzone/index.css
  components/menu/index.css
  components/search/index.css
  components/slider/index.css
  plugins/stylelint-no-unused-custom-properties/index.js
  stylelint.config.js
Labels: size-2 S, build, skip_vrt, ready-to-merge, skip_lint, s1

#3304 chore(swatch): remove unnecessary max nesting depth ignore comments
  components/swatch/index.css
Labels: size-1 XS, skip_vrt, ready-for-review

#3302 chore(steplist): remove unnecessary vertical-align declaration
  .changeset/strong-geese-yawn.md
  components/steplist/index.css
Labels: size-1 XS, skip_vrt, ready-to-merge

#3256 fix(actionbutton): prevent diacritic clipping in thai
  .changeset/calm-ears-think.md
  .changeset/fair-badgers-repeat.md
  components/actionbutton/index.css
  components/actionbutton/stories/actionbutton.test.js
  components/actiongroup/index.css
Labels: size-1 XS, skip_vrt, ready-to-merge, s1

#3226 feat(storybook): remove custom styles on storybook-root
  .storybook/assets/base.css
  components/alertbanner/stories/alertbanner.stories.js
  components/alertbanner/stories/alertbanner.test.js
  components/alertbanner/stories/template.js
  components/coachmark/stories/coachmark.stories.js
Labels: run_vrt, storybook, ready-to-merge, s1

#3296 chore(sidenav): move declaration, add description and apply token
  .changeset/chilly-cheetahs-study.md
  components/sidenav/index.css
Labels: size-1 XS, run_vrt, ready-for-review

#3315 chore(tabs): remove undefined/unused token
  .changeset/silly-kids-invite.md
  components/tabs/index.css
  components/tabs/metadata/metadata.json
Labels: size-1 XS, skip_vrt, ready-for-review

#3317 chore(tray): adjust declaration order to resovle lint violation
  .changeset/modern-clocks-obey.md
  components/tray/index.css
Labels: size-1 XS, run_vrt, ready-for-review

#3283 build: add lint and format to token assets
  .prettierignore
  tokens/custom-express/custom-dark-vars.css
  tokens/custom-express/custom-darkest-vars.css
  tokens/custom-express/custom-large-vars.css
  tokens/custom-express/custom-light-vars.css
  tokens/custom-express/custom-medium-vars.css
  tokens/custom-express/custom-vars.css
  tokens/custom-spectrum/custom-dark-vars.css
  tokens/custom-spectrum/custom-darkest-vars.css
  tokens/custom-spectrum/custom-large-vars.css
  tokens/custom-spectrum/custom-light-vars.css
  tokens/custom-spectrum/custom-medium-vars.css
  tokens/custom-spectrum/custom-vars.css
  tokens/dist/css/express/custom-large-vars.css
  tokens/dist/css/express/custom-medium-vars.css
  tokens/dist/css/express/custom-vars.css
  tokens/dist/css/express/dark-vars.css
  tokens/dist/css/express/darkest-vars.css
  tokens/dist/css/express/global-vars.css
  tokens/dist/css/express/large-vars.css
  tokens/dist/css/express/light-vars.css
  tokens/dist/css/express/medium-vars.css
  tokens/dist/css/spectrum/custom-large-vars.css
  tokens/dist/css/spectrum/custom-medium-vars.css
  tokens/dist/css/spectrum/custom-vars.css
  tokens/dist/css/spectrum/dark-vars.css
  tokens/dist/css/spectrum/darkest-vars.css
  tokens/dist/css/spectrum/global-vars.css
  tokens/dist/css/spectrum/large-vars.css
  tokens/dist/css/spectrum/light-vars.css
  tokens/dist/css/spectrum/medium-vars.css
  tokens/project.json
  tokens/tasks/token-rollup.js
  tokens/utilities/style-dictionary.utils.js
Labels: size-2 S, build, enhancement, skip_vrt, ready-to-merge

#3314 chore(thumbnail): remove unnecessary declarations + comments
  .changeset/lucky-schools-pay.md
  components/thumbnail/index.css
Labels: size-1 XS, skip_vrt, ready-for-review

#3325 chore(vscode-settings): remove deprecated property; disable postcss validate
  .vscode/settings.json
Labels: size-3 M, skip_vrt, ready-for-review

#3318 chore(treeview): remove unused custom property to resolve lint violation
  .changeset/nervous-steaks-provide.md
  components/treeview/index.css
Labels: size-1 XS, skip_vrt, ready-for-review

#3258 fix(clear button): align background color and hover state for disabled variant
  .changeset/silly-donkeys-remember.md
  components/clearbutton/index.css
  components/clearbutton/metadata/metadata.json
Labels: size-2 S, run_vrt, ready-for-review

#3292 fix(coachmark): correct invalid token pointers in pagination styles [CSS-1011]
  .changeset/lucky-experts-grow.md
  components/coachmark/index.css
  components/coachmark/metadata/metadata.json
Labels: bug, size-1 XS, skip_vrt, ready-to-merge, s1

#3348 chore(actionbutton): add tests for hovered, focused, actuve + selected
  components/actionbutton/stories/actionbutton.test.js
Labels: size-1 XS, run_vrt, ready-for-review

#3340 chore(stylelint): remove container from at-rule-no-unknown
  stylelint.config.js
Labels: size-1 XS, skip_vrt, ready-for-review

#3351 chore(tokens): use spectrum-tokens@13.0.0-beta.52
  .changeset/few-eels-retire.md
  tokens/dist/css/dark-vars.css
  tokens/dist/css/global-vars.css
  tokens/dist/css/large-vars.css
  tokens/dist/css/light-vars.css
  tokens/dist/css/medium-vars.css
  tokens/dist/index.css
  tokens/package.json
  yarn.lock
Labels: size-1 XS, skip_vrt, ready-for-review

#3297 fix(search): update icon sizing calculation in the quiet variant [CSS-1012]
  .changeset/dirty-suits-mix.md
  components/clearbutton/index.css
  components/search/index.css
  components/search/metadata/metadata.json
  components/search/metadata/mods.md
  components/search/stories/search.stories.js
Labels: bug, size-1 XS, run_vrt, ready-to-merge, s1

#3322 chore: dialog t-shirt sizing
  .changeset/nasty-pillows-wonder.md
  components/dialog/index.css
  components/dialog/metadata/metadata.json
Labels: size-1 XS, ready-for-review
