Repository adobe/spectrum-css, pull requests merged in 2024-06, with the labels that each got.

#2809 chore: remove duplicate express import from templates
  .storybook/guides/develop.mdx
  components/button/stories/button.stories.js
  components/button/stories/template.js
  components/icon/stories/icon.stories.js
  components/picker/stories/picker.stories.js
  components/picker/stories/template.js
  components/rating/stories/rating.stories.js
  components/rating/stories/template.js
Labels: testing, size-1 XS, express, skip_vrt, storybook, ready-for-review

#2811 chore(commons): run format tasks on commons assets
  components/commons/basebutton.css
  components/commons/overlay.css
Labels: size-1 XS, run_vrt, ready-for-review

#2674 feat(dropshadow): add dropshadow foundation
  .storybook/foundations/drop-shadow/drop-shadow.mdx
  .storybook/foundations/drop-shadow/drop-shadow.stories.js
  .storybook/foundations/drop-shadow/index.css
Labels: run_vrt, ready-to-merge

#2737 fix(picker): correct disabled state colors
  .changeset/sixty-pandas-impress.md
  components/picker/index.css
Labels: run_vrt, ready-for-review

#2821 feat(storybook): pull decorators into distinct files
  .changeset/light-roses-count.md
  .storybook/decorators/context.js
  .storybook/decorators/index.js
  .storybook/decorators/language.js
  .storybook/decorators/reducedMotion.js
  .storybook/decorators/sizing.js
  .storybook/decorators/testingPreview.js
  .storybook/decorators/textDirection.js
Labels: size-1 XS, enhancement, run_vrt, storybook, ready-for-review

#2825 chore(storybook): add formatting tool
  .storybook/DocumentationTemplate.mdx
  .storybook/assets/index.css
  .storybook/assets/typekit.js
  .storybook/decorators/context.js
  .storybook/decorators/sizing.js
  .storybook/decorators/testingPreview.js
  .storybook/decorators/textDirection.js
  .storybook/guides/code_of_conduct.mdx
  .storybook/guides/deprecation.mdx
  .storybook/guides/develop.mdx
  .storybook/guides/releasing.mdx
  .storybook/main.js
  .storybook/manager.js
  .storybook/preview.js
  .storybook/project.json
  .storybook/types/global.js
  .storybook/types/states.js
  nx.json
Labels: size-1 XS, ready-for-review

#2799 docs(icon): storybook documentation page
  components/icon/stories/icon.mdx
  components/icon/stories/icon.stories.js
Labels: documentation, size-1 XS, skip_vrt, ready-to-merge

#2842 fix: remove abstractions from build process for grid and keyframe
  .changeset/thin-jeans-wink.md
  postcss.config.js
Labels: bug, size-1 XS, run_vrt, ready-for-review

#2840 feat(storybook): move args to global scope
  .changeset/clever-bottles-wonder.md
  .storybook/decorators/context.js
  .storybook/decorators/helpers.js
  .storybook/decorators/index.js
  .storybook/decorators/language.js
  .storybook/decorators/reduce-motion.js
  .storybook/decorators/reducedMotion.js
  .storybook/decorators/sizing.js
  .storybook/decorators/testing-preview.js
  .storybook/decorators/text-direction.js
  .storybook/decorators/textDirection.js
  .storybook/guides/develop.mdx
  .storybook/package.json
  .storybook/preview.js
  .storybook/types/args.js
  .storybook/types/global.js
  .storybook/types/states.js
  components/actionmenu/stories/actionmenu.stories.js
  components/asset/stories/asset.stories.js
  components/avatar/stories/avatar.stories.js
  components/calendar/stories/calendar.stories.js
  components/calendar/stories/template.js
  components/coachmark/stories/coachmark.stories.js
  components/colorhandle/stories/colorhandle.stories.js
  components/combobox/stories/template.js
  components/datepicker/stories/template.js
  components/dialog/stories/dialog.stories.js
  components/dialog/stories/template.js
  components/helptext/stories/helptext.stories.js
  components/icon/stories/icon.stories.js
  components/pagination/stories/pagination.stories.js
  components/slider/stories/slider.stories.js
  components/slider/stories/template.js
  components/typography/stories/typography.stories.js
  tokens/custom-spectrum/custom-vars.css
  tokens/dist/css/spectrum/custom-vars.css
  tokens/dist/css/spectrum/global-vars.css
  tokens/dist/index.css
Labels: size-3 M, run_vrt, storybook, ready-for-review, high priority

#2697 feat(picker): migrate to spectrum 2
  .changeset/hot-books-fail.md
  components/picker/index.css
  components/picker/metadata/mods.md
  components/picker/metadata/picker.yml
  components/picker/package.json
  components/picker/stories/picker.stories.js
  components/picker/stories/template.js
  components/picker/themes/express.css
  components/picker/themes/spectrum.css
  yarn.lock
Labels: ready-for-review, S2

#2827 docs(dropzone,fieldgroup,floatingactionbutton,illustratedmessage,infieldbutton): site docs to Storybook
  .storybook/DocumentationTemplate.mdx
  .storybook/assets/base.css
  components/dropzone/stories/dropzone.stories.js
  components/dropzone/stories/template.js
  components/fieldgroup/stories/fieldgroup.mdx
  components/fieldgroup/stories/fieldgroup.stories.js
  components/fieldgroup/stories/template.js
  components/floatingactionbutton/stories/floatingactionbutton.stories.js
  components/illustratedmessage/stories/illustratedmessage.stories.js
  components/infieldbutton/stories/infieldbutton.stories.js
  components/infieldbutton/stories/template.js
  components/radio/stories/template.js
Labels: run_vrt, ready-for-review

#2771 feat: cleanup legacy vendor prefixes and normalization
  .changeset/tidy-balloons-cover.md
  components/accordion/index.css
  components/commons/basebutton.css
  components/statuslight/index.css
  components/textfield/index.css
Labels: run_vrt, ready-for-review

#2855 chore(dialog): z-index for dialog docs
  components/dialog/metadata/dialog.yml
  components/site/component.css
Labels: documentation, size-1 XS, skip_vrt, ready-to-merge

#2818 feat(statuslight): s2 migration
  .changeset/chilly-peaches-sniff.md
  components/statuslight/index.css
  components/statuslight/metadata/mods.md
  components/statuslight/metadata/statuslight.yml
  components/statuslight/stories/statuslight.stories.js
Labels: ready-to-merge, S2
