Repository adobe/spectrum-css, pull requests merged in 2024-04, with the labels that each got.

#2618 refactor(tokens): remove some unused custom variables
  tokens/custom-spectrum/custom-large-vars.css
  tokens/custom-spectrum/custom-medium-vars.css
  tokens/dist/css/spectrum/custom-large-vars.css
  tokens/dist/css/spectrum/custom-medium-vars.css
  tokens/dist/index.css
Labels: run_vrt

#2444 refactor(card): rename mod and refactor some usage of mods and vars
  components/card/index.css
  components/card/metadata/mods.md
Labels: run_vrt, ready-to-merge

#2629 ci: ensure the shas used by compare match the current PR
  .github/workflows/development.yml
Labels: skip_vrt, ready-to-merge

#2630 chore: align commons version with npm
  components/actionbutton/package.json
  components/button/package.json
  components/closebutton/package.json
  components/commons/package.json
  components/modal/package.json
  components/popover/package.json
  components/tooltip/package.json
  components/underlay/package.json
Labels: size-1 XS, run_vrt, ready-for-review

#2631 fix(logicbutton,picker): add missing commons devDep
  components/logicbutton/package.json
  components/picker/package.json
Labels: run_vrt, ready-for-review

#2634 ci: base and head ref fix
  .github/workflows/development.yml
  .github/workflows/production.yml
  .github/workflows/publish-site.yml
  .github/workflows/vrt.yml
Labels: run_vrt, ready-for-review

#2633 chore(logicbutton,picker): align commons package
  components/logicbutton/package.json
  components/picker/package.json
Labels: skip_vrt, ready-for-review, S2

#2635 ci: support slashes in branch names
  .github/workflows/build.yml
  .github/workflows/compare-results.yml
  .github/workflows/production.yml
  .github/workflows/publish-site.yml
  .github/workflows/vrt.yml
Labels: skip_vrt, ready-for-review

#2346 build: hardening linter settings
  .eslintignore
  .eslintrc
  .gitignore
  .prettierignore
  .stylelintignore
  nx.json
  package.json
  plugins/stylelint-no-missing-var/index.js
  plugins/stylelint-no-missing-var/project.json
  plugins/stylelint-no-missing-var/test.js
  plugins/stylelint-no-unknown-custom-properties/index.js
  plugins/stylelint-no-unknown-custom-properties/project.json
  plugins/stylelint-no-unknown-custom-properties/test.js
  plugins/stylelint-no-unused-custom-properties/expected/unused.css
  plugins/stylelint-no-unused-custom-properties/expected/varRefs.css
  plugins/stylelint-no-unused-custom-properties/index.js
  plugins/stylelint-no-unused-custom-properties/project.json
  plugins/stylelint-no-unused-custom-properties/test.js
  yarn.lock
Labels: build, skip_vrt, ready-for-review

#2650 feat(tokens): v13.0.0-beta.24
  tokens/dist/css/dark-vars.css
  tokens/dist/css/global-vars.css
  tokens/dist/css/large-vars.css
  tokens/dist/css/light-vars.css
  tokens/dist/css/medium-vars.css
  tokens/dist/index.css
  tokens/package.json
  yarn.lock
Labels: run_vrt

#2656 chore: flag private packages
  .github/actions/file-diff/package.json
  plugins/stylelint-no-missing-var/package.json
  plugins/stylelint-no-unknown-custom-properties/package.json
  plugins/stylelint-no-unused-custom-properties/package.json
  site/package.json
Labels: size-1 XS, skip_vrt, ready-for-review

#2661 feat(card): overflow hidden on cover photo for swc implementation
  components/card/index.css
Labels: run_vrt

#2546 build: upgrade to yarn 4.1.1
  .gitattributes
  .github/actions/file-diff/package.json
  .github/workflows/build.yml
  .github/workflows/compare-results.yml
  .github/workflows/lint.yml
  .github/workflows/publish-site.yml
  .github/workflows/vrt.yml
  .gitignore
  .yarn/releases/yarn-4.1.1.cjs
  .yarnrc.yml
  package.json
  plugins/stylelint-no-missing-var/package.json
  plugins/stylelint-no-unknown-custom-properties/package.json
  plugins/stylelint-no-unused-custom-properties/package.json
  site/package.json
  yarn.lock
Labels: build, skip_vrt, ready-to-merge

#2675 chore: fix eslint formatting command
  components/checkbox/stories/template.js
  components/fieldlabel/stories/template.js
  components/icon/stories/template.js
  components/inlinealert/stories/template.js
  components/menu/stories/template.js
  components/picker/stories/template.js
  components/progresscircle/stories/template.js
  components/stepper/stories/template.js
  nx.json
Labels: skip_vrt, ready-for-review

#2678 chore(tokens): use @adobe/spectrum-tokens@13.0.0-beta.30
  .changeset/pretty-parents-drum.md
  tokens/dist/css/global-vars.css
  tokens/dist/css/large-vars.css
  tokens/dist/css/medium-vars.css
  tokens/dist/index.css
  tokens/package.json
  yarn.lock
Labels: run_vrt

#2676 chore: remove unused conventional changelog package
  package.json
  plugins/conventional-changelog-spectrum/CHANGELOG.md
  plugins/conventional-changelog-spectrum/LICENSE.md
  plugins/conventional-changelog-spectrum/README.md
  plugins/conventional-changelog-spectrum/conventional-changelog.js
  plugins/conventional-changelog-spectrum/conventional-recommended-bump.js
  plugins/conventional-changelog-spectrum/index.js
  plugins/conventional-changelog-spectrum/package.json
  plugins/conventional-changelog-spectrum/parser-opts.js
  plugins/conventional-changelog-spectrum/templates/commit.hbs
  plugins/conventional-changelog-spectrum/templates/footer.hbs
  plugins/conventional-changelog-spectrum/templates/header.hbs
  plugins/conventional-changelog-spectrum/templates/template.hbs
  plugins/conventional-changelog-spectrum/test/fixtures/_ghe-host.json
  plugins/conventional-changelog-spectrum/test/fixtures/_known-host.json
  plugins/conventional-changelog-spectrum/test/fixtures/_unknown-host.json
  plugins/conventional-changelog-spectrum/test/test.js
  plugins/conventional-changelog-spectrum/writer-opts.js
  yarn.lock
Labels: skip_vrt, ready-for-review

#2682 chore: minor workflow updates
  .env.example
  lerna.json
  package.json
Labels: skip_vrt

#2671 build: update node dependency from v18 to v20
  .changeset/five-panthers-wonder.md
  .github/workflows/build.yml
  .github/workflows/compare-results.yml
  .github/workflows/development.yml
  .github/workflows/lint.yml
  .github/workflows/production.yml
  .github/workflows/publish-site.yml
  .github/workflows/vrt.yml
  .nvmrc
  .storybook/guides/develop.mdx
  package.json
Labels: build, run_vrt, ready-for-review

#2700 chore: run branch through format; update pathing and fix errors
  .changeset/perfect-dogs-smash.md
  .storybook/package.json
  components/actionbutton/metadata/mods.md
  components/actiongroup/CHANGELOG.md
  components/button/index.css
  components/button/metadata/mods.md
  components/button/stories/button.stories.js
  components/buttongroup/CHANGELOG.md
  components/checkbox/package.json
  components/clearbutton/package.json
  components/closebutton/metadata/mods.md
  components/closebutton/package.json
  components/closebutton/stories/template.js
  components/datepicker/package.json
  components/dial/package.json
  components/divider/package.json
  components/fieldlabel/metadata/fieldlabel.yml
  components/fieldlabel/package.json
  components/fieldlabel/stories/template.js
  components/logicbutton/metadata/mods.md
  components/logicbutton/package.json
  components/miller/package.json
  components/modal/package.json
  components/opacitycheckerboard/package.json
  components/page/package.json
  components/picker/metadata/mods.md
  components/pickerbutton/package.json
  components/progresscircle/package.json
  components/radio/package.json
  components/search/package.json
  components/slider/package.json
  components/splitview/package.json
  components/swatch/package.json
  components/switch/index.css
  components/switch/package.json
  components/toast/package.json
  components/tooltip/package.json
  components/underlay/package.json
  yarn.lock
Labels: ready-for-review, S2
