Repository adobe/spectrum-css, pull requests merged in 2024-01, with the labels that each got.

#2396 chore(ci): correct the direction of diff equations
  .github/actions/file-diff/README.md
  .github/actions/file-diff/action.yml
  .github/actions/file-diff/index.js
  .github/workflows/compare-results.yml
  .vscode/settings.json
Labels: size-1 XS, skip_vrt, github_actions

#2402 chore: update build script used in chromatic config
  .env.example
Labels: size-1 XS, skip_vrt, storybook, ready-for-review

#2404 chore: remove unused package linter script
  tasks/packageLint.js
Labels: size-1 XS, skip_vrt, ready-for-review

#2405 chore: update compare script to fix an issue when runs are parallelized
  README.md
  package.json
  tasks/compare-compiled-output.js
Labels: size-1 XS, skip_vrt, ready-for-review

#2407 build: allow empty theme assets during build step
  tools/component-builder-simple/css/index.js
  tools/component-builder/css/lib/varUtils.js
  tools/component-builder/css/vars.js
Labels: size-1 XS, build, run_vrt, ready-for-review

#2414 chore(storybook): align package versions for @storybook/*
  .storybook/package.json
  yarn.lock
Labels: size-2 S, run_vrt, storybook, ready-for-review

#2384 fix(stepper): express whcm
  components/stepper/index.css
Labels: ready-to-merge

#2375 refactor(combobox): use sub component mod properties
  components/combobox/index.css
  components/combobox/metadata/combobox.yml
  components/combobox/stories/template.js
  site/resources/js/enhancement.js
Labels: run_vrt

#2435 fix(tokens): dependency updates
  tokens/dist/css/dark-vars.css
  tokens/dist/css/darkest-vars.css
  tokens/dist/css/express/custom-dark-vars.css
  tokens/dist/css/express/custom-darkest-vars.css
  tokens/dist/css/express/custom-large-vars.css
  tokens/dist/css/express/custom-light-vars.css
  tokens/dist/css/express/custom-medium-vars.css
  tokens/dist/css/express/custom-vars.css
  tokens/dist/css/express/global-vars.css
  tokens/dist/css/express/large-vars.css
  tokens/dist/css/express/medium-vars.css
  tokens/dist/css/global-vars.css
  tokens/dist/css/large-vars.css
  tokens/dist/css/light-vars.css
  tokens/dist/css/medium-vars.css
  tokens/dist/css/spectrum/custom-dark-vars.css
  tokens/dist/css/spectrum/custom-darkest-vars.css
  tokens/dist/css/spectrum/custom-large-vars.css
  tokens/dist/css/spectrum/custom-light-vars.css
  tokens/dist/css/spectrum/custom-medium-vars.css
  tokens/dist/css/spectrum/custom-vars.css
  tokens/dist/css/spectrum/global-vars.css
  tokens/dist/css/spectrum/large-vars.css
  tokens/dist/css/spectrum/medium-vars.css
  tokens/dist/index.css
  tokens/package.json
  yarn.lock
Labels: size-3 M, tokens, run_vrt, ready-for-review

#2415 fix(table): replace leftover global color token
  components/table/index.css
Labels: run_vrt

#2423 fix(commons): rename and deprecate mods referencing global tokens
  components/actionbutton/metadata/mods.md
  components/button/metadata/mods.md
  components/closebutton/metadata/mods.md
  components/commons/basebutton-coretokens.css
  components/logicbutton/metadata/mods.md
  components/picker/metadata/mods.md
Labels: skip_vrt

#2377 fix(picker): rename is-focused class to is-keyboardFocused
  components/picker/index.css
  components/picker/stories/picker.stories.js
  components/picker/stories/template.js
Labels: size-1 XS, run_vrt, ready-for-review

#2438 feat(asset,cyclebutton,quickaction,site): deprecate skin.css assets
  components/README.md
  components/asset/index.css
  components/asset/skin.css
  components/asset/stories/template.js
  components/cyclebutton/skin.css
  components/quickaction/index.css
  components/quickaction/skin.css
  components/quickaction/stories/template.js
  components/site/index.css
  components/site/skin.css
  tools/component-builder/css/index.js
Labels: size-2 S, run_vrt, ready-for-review

#2441 fix(card): revert misnamed instance of background color mod
  components/card/index.css
Labels: run_vrt

#2446 fix(quickaction): storybook using wrong root class
  components/quickaction/stories/quickaction.stories.js
Labels: run_vrt

#2442 fix(checkbox): address typo
  components/checkbox/index.css
Labels: run_vrt

#2454 ci: allow spectrum-two PRs
  .github/workflows/development.yml
  .github/workflows/production.yml
Labels: skip_vrt

#2475 chore: incorporate ui-icons build into prerelease task
  package.json
Labels: skip_vrt, ready-to-merge
