Repository adobe/spectrum-css, pull requests merged in 2024-05, with the labels that each got.

#2696 chore: storybook context application
  .storybook/decorators/contextsWrapper.js
  components/button/stories/template.js
  components/progresscircle/stories/progresscircle.stories.js
  components/progresscircle/stories/template.js
Labels: run_vrt, ready-for-review

#2726 chore: update minor versions in dependent packages
  .changeset/fresh-foxes-flow.md
  .github/actions/file-diff/package.json
  .storybook/package.json
  generator/package.json
  generator/plopfile.js
  package.json
  plugins/postcss-combininator/package.json
  plugins/postcss-custom-properties-mapping/package.json
  plugins/postcss-splitinator/package.json
  plugins/stylelint-no-missing-var/package.json
  plugins/stylelint-no-unknown-custom-properties/package.json
  plugins/stylelint-no-unused-custom-properties/package.json
  site/package.json
  tokens/package.json
  ui-icons/package.json
  yarn.lock
Labels: dependencies, build, run_vrt, ready-for-review

#2616 feat: cssnano optimizations
  .changeset/swift-teachers-warn.md
  .prettierrc
  lint-staged.config.js
  package.json
  postcss.config.js
  tasks/component-builder.js
  yarn.lock
Labels: size-2 S, build, enhancement, skip_vrt, ready-for-review

#2729 chore: add deprecation notes to storybook docs; support mdx assets for components
  .storybook/deprecated/cyclebutton/cyclebutton.stories.js
  .storybook/deprecated/quickaction/quickaction.stories.js
  .storybook/deprecated/searchwithin/searchwithin.stories.js
  .storybook/deprecated/splitbutton/splitbutton.stories.js
  .storybook/main.js
  .storybook/preview.js
Labels: documentation, size-1 XS, skip_vrt, storybook, ready-for-review

#2736 fix(tooltip): rtl places tip in correct position
  .changeset/kind-mangos-jam.md
  components/tooltip/index.css
  components/tooltip/metadata/tooltip.yml
  components/tooltip/stories/tooltip.stories.js
Labels: run_vrt, ready-for-review

#2659 feat(progressbar): s2 migration
  .changeset/proud-jokes-rule.md
  .storybook/decorators/contextsWrapper.js
  components/progressbar/index.css
  components/progressbar/metadata/progressbar.yml
  components/progressbar/package.json
  components/progressbar/stories/progressbar.stories.js
  components/progressbar/stories/template.js
  yarn.lock
Labels: run_vrt

#2754 feat: define missing color property in some components
  .changeset/new-sheep-bathe.md
  components/datepicker/index.css
  components/datepicker/metadata/mods.md
  components/progressbar/stories/meter.template.js
  components/radio/index.css
  components/slider/index.css
  components/slider/metadata/mods.md
  components/splitview/index.css
  components/splitview/metadata/mods.md
  components/treeview/index.css
  components/well/index.css
  components/well/metadata/mods.md
Labels: run_vrt

#2756 chore: fix loglevel error message when running prettier commands
  lint-staged.config.js
  nx.json
Labels: size-1 XS, skip_vrt, ready-to-merge

#2672 chore: minor fixes in build workflow and package alignment
  .storybook/project.json
  nx.json
  package.json
  site/package.json
  site/project.json
  yarn.lock
Labels: build, skip_vrt, ready-to-merge

#2745 fix(popover): no more duplicate class selectors in dist
  .changeset/tidy-olives-notice.md
  components/popover/index.css
Labels: run_vrt, ready-to-merge

#2761 fix(textfield): no pointer events for focus pseudo element
  .changeset/lazy-rivers-leave.md
  components/textfield/index.css
Labels: run_vrt, ready-for-review

#2762 feat(alertbanner): use width token for max-width instead of width
  .changeset/brave-seas-retire.md
  components/alertbanner/index.css
  components/alertbanner/metadata/mods.md
Labels: run_vrt, ready-for-review

#2770 docs(accordion,actionbar,actionmenu,alertdialog): site docs to storybook
  .storybook/guides/develop.mdx
  .storybook/manager.js
  components/accordion/stories/accordion.mdx
  components/accordion/stories/accordion.stories.js
  components/actionbar/stories/actionbar.mdx
  components/actionbar/stories/actionbar.stories.js
  components/actionmenu/stories/actionmenu.stories.js
  components/alertdialog/stories/alertdialog.mdx
  components/alertdialog/stories/alertdialog.stories.js
  components/alertdialog/stories/template.js
Labels: skip_vrt

#2744 fix(slider,radio): dir before pseudo element
  .changeset/neat-windows-yawn.md
  components/radio/index.css
  components/slider/index.css
Labels: skip_vrt, ready-to-merge

#2775 chore(deps): minor dependency updates across the project
  .changeset/pretty-goats-act.md
  .github/actions/file-diff/package.json
  .storybook/package.json
  generator/package.json
  package.json
  plugins/postcss-combininator/package.json
  plugins/stylelint-no-missing-var/package.json
  plugins/stylelint-no-unknown-custom-properties/package.json
  plugins/stylelint-no-unused-custom-properties/package.json
  yarn.lock
Labels: skip_vrt, ready-for-review

#2753 fix(popover): correct left/right tips for RTL, increase VRT coverage
  .changeset/three-geese-relax.md
  components/popover/index.css
  components/popover/stories/popover.stories.js
  components/popover/stories/template.js
Labels: skip_vrt

#2782 docs(asset,assetcard,avatar,badge): site docs to storybook
  components/asset/stories/asset.mdx
  components/asset/stories/asset.stories.js
  components/assetcard/stories/assetcard.mdx
  components/avatar/stories/avatar.mdx
  components/avatar/stories/avatar.stories.js
  components/badge/stories/badge.mdx
  components/badge/stories/badge.stories.js
Labels: run_vrt, ready-to-merge

#2787 docs(colorhandle,colorloupe,colorslider,colorwheel): site docs to storybook
  components/colorhandle/stories/colorhandle.mdx
  components/colorhandle/stories/colorhandle.stories.js
  components/colorhandle/stories/template.js
  components/colorloupe/stories/colorloupe.mdx
  components/colorslider/stories/colorslider.mdx
  components/colorwheel/stories/colorwheel.mdx
  components/colorwheel/stories/colorwheel.stories.js
  components/colorwheel/stories/template.js
Labels: run_vrt, ready-to-merge

#2783 docs(calendar,card,coachmark,colorarea): site docs to storybook
  components/asset/stories/template.js
  components/calendar/stories/calendar.mdx
  components/calendar/stories/calendar.stories.js
  components/calendar/stories/template.js
  components/card/stories/card.mdx
  components/card/stories/card.stories.js
  components/card/stories/template.js
  components/coachmark/stories/coachmark.mdx
  components/coachmark/stories/coachmark.stories.js
  components/coachmark/stories/template.js
  components/colorarea/stories/colorarea.mdx
  components/colorarea/stories/colorarea.stories.js
Labels: run_vrt, ready-to-merge

#2752 fix(slider): use high contrast properties and fix ramp handle circle
  .changeset/eight-crabs-smile.md
  components/slider/index.css
Labels: run_vrt, ready-for-review, ready-to-merge

#2725 refactor(button): remove spectrum-ButtonWithFocusRing extend
  .changeset/fresh-seahorses-join.md
  components/button/index.css
  components/button/metadata/mods.md
Labels: run_vrt, ready-for-review, S2

#2794 docs(combobox,contextualhelp,datepicker): site docs to storybook
  components/combobox/CHANGELOG.md
  components/combobox/stories/combobox.mdx
  components/combobox/stories/combobox.stories.js
  components/contextualhelp/stories/contextualhelp.mdx
  components/contextualhelp/stories/contextualhelp.stories.js
  components/datepicker/CHANGELOG.md
  components/datepicker/stories/datepicker.mdx
  components/datepicker/stories/datepicker.stories.js
  components/datepicker/stories/template.js
Labels: run_vrt, ready-for-review
