Repository adobe/spectrum-css, pull requests merged in 2024-09, with the labels that each got.

#3067 fix(ComponentDetails): apply sb-unstyled className to correct version number misalignment
  .changeset/seven-ways-search.md
  .storybook/blocks/ComponentDetails.jsx
Labels: size-1 XS, skip_vrt, ready-for-review

#3012 fix(textfield + stepper): allow is-disabled to supersede invalid and focus states
  .changeset/nasty-drinks-scream.md
  components/stepper/index.css
  components/stepper/metadata/metadata.json
  components/stepper/stories/stepper.test.js
  components/textfield/index.css
  components/textfield/metadata/metadata.json
Labels: run_vrt, ready-for-review

#3069 docs(button): custom storybook docs from spectrum-two
  components/button/stories/button.mdx
  components/button/stories/button.stories.js
  components/button/stories/template.js
Labels: documentation, run_vrt, ready-for-review

#2883 docs(popover, progresscircle, radio, rating, sidenav): site docs to storybook
  .storybook/decorators/utilities.js
  .storybook/types/states.js
  components/datepicker/stories/datepicker.test.js
  components/fieldgroup/stories/fieldgroup.test.js
  components/fieldgroup/stories/template.js
  components/popover/stories/popover.stories.js
  components/popover/stories/popover.test.js
  components/popover/stories/template.js
  components/progresscircle/CHANGELOG.md
  components/progresscircle/stories/progresscircle.stories.js
  components/progresscircle/stories/template.js
  components/radio/stories/radio.stories.js
  components/radio/stories/radio.test.js
  components/radio/stories/template.js
  components/rating/stories/rating.stories.js
  components/rating/stories/rating.test.js
  components/rating/stories/template.js
  components/sidenav/stories/sidenav.stories.js
  components/sidenav/stories/sidenav.test.js
  components/sidenav/stories/template.js
Labels: documentation, run_vrt, ready-for-review

#3075 chore(card): storybook component fixes
  components/card/stories/template.js
Labels: run_vrt, ready-for-review

#3085 fix(storybook): token and typography loading
  .changeset/swift-mice-teach.md
  .storybook/assets/base.css
  .storybook/assets/index.css
  .storybook/decorators/context.js
  .storybook/decorators/helpers.js
  .storybook/decorators/utilities.js
  .storybook/loaders/index.js
  .storybook/loaders/token-loader.js
  .storybook/preview.js
  components/typography/stories/template.js
Labels: size-3 M, run_vrt, storybook, ready-for-review

#3072 fix(card -> action button): corrects the size and alignment of the card action button
  .changeset/selfish-readers-wave.md
  components/card/index.css
Labels: run_vrt, ready-for-review

#3049 fix(button, SWC-342): update content-color for primary s2 button
  .changeset/shiny-peaches-change.md
  components/button/metadata/metadata.json
  components/button/themes/spectrum-two.css
  components/button/themes/spectrum.css
Labels: run_vrt, ready-for-review

#3073 fix(toast): added overflow css to toast for long words
  .changeset/cyan-fishes-punch.md
  components/toast/index.css
Labels: run_vrt

#3098 chore(card): import Divider and remove static hr from card story
  components/card/stories/template.js
Labels: run_vrt, ready-for-review

#3106 chore(storybook): add env variable for local testing
  .storybook/package.json
  .storybook/project.json
Labels: testing, size-1 XS, build, skip_vrt, ready-for-review

#3103 fix(stepper): corrects invalid button color border to match field in windows high contrast mode
  .changeset/clever-seas-smell.md
  components/stepper/index.css
  components/stepper/metadata/metadata.json
Labels: run_vrt, ready-for-review

#3089 fix(treeview): display corner rounding for detached treeview
  .changeset/loud-pandas-act.md
  components/treeview/index.css
  components/treeview/stories/template.js
  components/treeview/stories/treeview.stories.js
  components/treeview/stories/treeview.test.js
Labels: run_vrt, ready-to-merge

#3108 feat(closebutton): fix close button sizing class name
  .changeset/many-eels-protect.md
  components/closebutton/index.css
  components/closebutton/metadata/metadata.json
  components/closebutton/stories/closebutton.stories.js
  components/closebutton/stories/closebutton.test.js
  components/closebutton/stories/template.js
Labels: bug, size-2 S, run_vrt, ready-for-review

#3120 fix: resolve error in typography story template
  components/typography/stories/typography.stories.js
Labels: size-1 XS, run_vrt, storybook, ready-for-review

#3079 fix(calendar): addresses issue where text that was not selected was illegible in high contrast mode
  .changeset/lemon-tools-look.md
  components/calendar/index.css
Labels: run_vrt

#3105 fix(avatar): remove outline and reduce redundancy
  .changeset/ninety-peas-approve.md
  components/avatar/index.css
Labels: run_vrt, ready-for-review

#3078 fix(button -> negative): corrects interior label background color to align with parent
  .changeset/little-cows-hang.md
  components/button/index.css
  components/button/metadata/metadata.json
Labels: run_vrt, ready-for-review

#3077 docs(closebutton): migrate docs to storybook and add missing control
  components/closebutton/metadata/closebutton.yml
  components/closebutton/stories/closebutton.stories.js
  components/closebutton/stories/template.js
Labels: documentation, run_vrt, ready-for-review

#2925 docs(swatch,swatchgroup,table,tabs): docs migrations to storybook
  components/swatch/stories/swatch.stories.js
  components/swatch/stories/swatch.test.js
  components/swatch/stories/template.js
  components/swatchgroup/stories/swatchgroup.stories.js
  components/swatchgroup/stories/swatchgroup.test.js
  components/swatchgroup/stories/template.js
  components/table/CHANGELOG.md
  components/table/stories/table.stories.js
  components/table/stories/table.test.js
  components/table/stories/template.js
  components/tabs/CHANGELOG.md
  components/tabs/stories/tabs.stories.js
  components/tabs/stories/tabs.test.js
  components/tabs/stories/template.js
Labels: size-2 S, run_vrt, storybook, ready-for-review

#3123 chore(stepper): update vrt snapshots
  components/stepper/stories/stepper.stories.js
  components/stepper/stories/stepper.test.js
  components/stepper/stories/template.js
Labels: testing, size-1 XS, run_vrt, ready-for-review, high priority, s1

#3119 fix(slider): adds space between side positioned label and slider
  .changeset/flat-tips-knock.md
  components/slider/index.css
  components/slider/metadata/metadata.json
Labels: run_vrt, ready-for-review, s1

#3130 docs(button): increase coverage of outline variants
  components/button/stories/button.test.js
Labels: run_vrt, ready-for-review, s1

#3025 chore(dropindicator): update storybook prop to use length instead of size
  components/dropindicator/stories/dropindicator.stories.js
  components/dropindicator/stories/template.js
Labels: size-1 XS, run_vrt, storybook, ready-for-review, s1

#3136 chore(contextualhelp): docs page fix
  components/contextualhelp/stories/contextualhelp.mdx
  components/datepicker/stories/datepicker.mdx
Labels: size-1 XS, skip_vrt, ready-for-review, s1

#3138 docs(icon): fix ui icons not displaying in storybook
  components/icon/stories/template.js
Labels: run_vrt, ready-for-review

#3137 fix(tokens,well): border color mapping
  .changeset/late-wombats-begin.md
  tokens/custom-spectrum/custom-light-vars.css
  tokens/dist/css/spectrum/light-vars.css
  tokens/dist/index.css
Labels: size-1 XS, run_vrt, ready-for-review, s1

#3139 docs(typography): add tagged releases
  .changeset/shiny-balloons-remember.md
  components/typography/stories/typography.mdx
  generator/templates/stories/{{ folderName }}.mdx.hbs
Labels: size-1 XS, skip_vrt, storybook, ready-for-review, s1

#3086 feat(button): add label text wrap option
  .changeset/green-maps-end.md
  components/button/index.css
  components/button/metadata/metadata.json
  components/button/metadata/mods.md
  components/button/stories/button.mdx
  components/button/stories/button.stories.js
  components/button/stories/button.test.js
  components/button/stories/template.js
Labels: ready-for-review, s1

#3151 docs(helptext): migrate docs to storybook
  components/helptext/stories/helptext.stories.js
  components/helptext/stories/template.js
Labels: run_vrt, ready-to-merge

#3143 fix(storybook): updates to pass the correct content types to the dialog and popover components
  components/button/stories/template.js
  components/buttongroup/stories/template.js
  components/dialog/stories/dialog.stories.js
  components/popover/stories/popover.stories.js
Labels: ready-for-review

#3161 chore: fix logic in file-diff github action
  .github/actions/file-diff/index.js
Labels: size-1 XS, skip_vrt, ready-for-review, s1

#3157 docs(buttongroup): adding vertical horizontal and disabled stories
  components/buttongroup/metadata/buttongroup.yml
  components/buttongroup/stories/buttongroup.stories.js
  components/buttongroup/stories/buttongroup.test.js
Labels: run_vrt, storybook, ready-for-review, s1

#3131 chore(storybook): align display viewports for stories
  .changeset/ten-olives-call.md
  .storybook/assets/base.css
  .storybook/decorators/index.js
  .storybook/decorators/sizing.js
  .storybook/decorators/utilities.js
  .storybook/modes/index.js
  .storybook/preview.js
  components/alertbanner/stories/alertbanner.stories.js
  components/alertbanner/stories/template.js
  components/alertdialog/stories/alertdialog.stories.js
  components/coachindicator/stories/coachindicator.stories.js
  components/coachmark/stories/coachmark.stories.js
  components/coachmark/stories/template.js
  components/colorarea/stories/colorarea.test.js
  components/colorhandle/stories/colorhandle.stories.js
  components/contextualhelp/stories/contextualhelp.stories.js
  components/dialog/stories/dialog.stories.js
  components/icon/stories/icon.stories.js
  components/menu/stories/menu.stories.js
  components/modal/index.css
  components/popover/stories/popover.stories.js
  components/tray/stories/tray.stories.js
  components/underlay/stories/underlay.stories.js
Labels: size-5 L, run_vrt, storybook, ready-for-review

#3163 chore(storybook): support sizing for swatch docblocks
  .storybook/assets/base.css
  .storybook/assets/images/gradient-background-dark.png
  .storybook/assets/images/gradient-background-light.png
  .storybook/blocks/ColorPalette.jsx
  .storybook/blocks/ComponentDetails.jsx
  .storybook/blocks/ThemeContainer.jsx
  .storybook/guides/color_palette.mdx
Labels: size-1 XS, run_vrt, ready-for-review, s1

#3173 build: commons reporting bug fix
  components/commons/project.json
Labels: size-1 XS, build, skip_vrt, ready-for-review, s1

#3144 docs(tooltip): docs site to storybook
  components/tooltip/stories/template.js
  components/tooltip/stories/tooltip.stories.js
Labels: skip_vrt, storybook, ready-to-merge, s1

#3155 docs: ensure that icon set is defined throughout storybook
  .storybook/deprecated/quickaction/quickaction.stories.js
  .storybook/deprecated/splitbutton/splitbutton.stories.js
  components/actionbar/stories/template.js
  components/actionbutton/stories/template.js
  components/actiongroup/stories/actiongroup.stories.js
  components/actionmenu/stories/actionmenu.test.js
  components/actionmenu/stories/template.js
  components/alertbanner/stories/template.js
  components/alertdialog/stories/template.js
  components/assetlist/stories/assetlist.stories.js
  components/assetlist/stories/template.js
  components/badge/stories/badge.stories.js
  components/badge/stories/template.js
  components/breadcrumb/stories/breadcrumb.stories.js
  components/breadcrumb/stories/breadcrumb.test.js
  components/breadcrumb/stories/template.js
  components/button/stories/button.stories.js
  components/button/stories/button.test.js
  components/button/stories/template.js
  components/card/stories/template.js
  components/checkbox/stories/template.js
  components/clearbutton/stories/template.js
  components/closebutton/stories/template.js
  components/coachmark/stories/template.js
  components/combobox/stories/template.js
  components/contextualhelp/stories/contextualhelp.stories.js
  components/contextualhelp/stories/template.js
  components/datepicker/stories/template.js
  components/floatingactionbutton/stories/floatingactionbutton.stories.js
  components/floatingactionbutton/stories/template.js
  components/helptext/stories/template.js
  components/infieldbutton/stories/template.js
  components/inlinealert/stories/template.js
  components/menu/stories/menu.test.js
  components/pagination/stories/template.js
  components/picker/stories/template.js
  components/pickerbutton/stories/pickerbutton.stories.js
  components/pickerbutton/stories/template.js
  components/rating/stories/template.js
  components/sidenav/stories/sidenav.test.js
  components/sidenav/stories/template.js
  components/stepper/stories/template.js
  components/table/stories/template.js
  components/tabs/stories/template.js
  components/tag/stories/template.js
  components/toast/stories/template.js
  components/tooltip/stories/template.js
Labels: run_vrt, ready-for-review, s1

#3134 docs(menu): docs site to storybook
  components/menu/stories/menu.stories.js
  components/menu/stories/menu.test.js
  components/menu/stories/template.js
Labels: run_vrt, storybook, ready-to-merge, s1
