Repository adobe/spectrum-css, pull requests merged in 2024-07, with the labels that each got.

#2861 fix(dialog): implement dialog button groups
  components/dialog/metadata/dialog.yml
  components/dialog/package.json
  yarn.lock
Labels: ready-for-review

#2867 feat(storybook): add the swc preview
  .changeset/dull-coats-pull.md
  .storybook/main.js
Labels: enhancement, skip_vrt, ready-for-review

#2915 fix(storybook): some inline stories in docs cutting off
  .storybook/assets/base.css
Labels: run_vrt, ready-for-review

#2914 fix(picker): prevent diacritic text cutoff
  .changeset/nasty-moose-act.md
  components/picker/index.css
  components/picker/stories/picker.stories.js
Labels: run_vrt, ready-for-review

#2743 feat(tooltip): S2 migration
  .changeset/light-years-speak.md
  components/tooltip/index.css
  components/tooltip/metadata/mods.md
  components/tooltip/metadata/tooltip.yml
  components/tooltip/package.json
  components/tooltip/stories/template.js
  components/tooltip/stories/tooltip.stories.js
  tokens/custom-spectrum/custom-large-vars.css
  tokens/custom-spectrum/custom-medium-vars.css
  tokens/dist/css/spectrum/custom-large-vars.css
  tokens/dist/css/spectrum/custom-medium-vars.css
  tokens/dist/index.css
  yarn.lock
Labels: S2, design-approved

#2927 chore: husky script changes on install
  .husky/commit-msg
  .husky/pre-commit
Labels: size-1 XS, build, skip_vrt, ready-for-review

#2936 chore(storybook): update fixed port to 8080
  .storybook/main.js
  .storybook/project.json
Labels: size-1 XS, skip_vrt, storybook, ready-for-review

#2780 feat: upgrade stylelint use and plugins to support v16
  .changeset/healthy-pens-grab.md
  .github/workflows/development.yml
  components/combobox/index.css
  package.json
  plugins/stylelint-no-missing-var/index.js
  plugins/stylelint-no-missing-var/package.json
  plugins/stylelint-no-missing-var/test.js
  plugins/stylelint-no-unknown-custom-properties/index.js
  plugins/stylelint-no-unknown-custom-properties/package.json
  plugins/stylelint-no-unknown-custom-properties/test.js
  plugins/stylelint-no-unused-custom-properties/index.js
  plugins/stylelint-no-unused-custom-properties/package.json
  plugins/stylelint-no-unused-custom-properties/test.js
  stylelint.config.js
  yarn.lock
Labels: skip_vrt, ready-for-review

#2935 chore(build): add additional metadata for mapping to improve map paths
  tasks/component-builder.js
Labels: size-1 XS, build, skip_vrt, ready-for-review

#2931 chore(storybook): organize icon loader into tooling
  .storybook/decorators/icon-sprites.js
  .storybook/decorators/index.js
  .storybook/loaders/icon-loader.js
  .storybook/loaders/index.js
  .storybook/preview.js
Labels: size-1 XS, run_vrt, storybook, ready-to-merge

#2934 feat(storybook): global types configuration
  .changeset/purple-chicken-press.md
  .storybook/decorators/arg-events.js
  .storybook/decorators/context.js
  .storybook/decorators/utilities.js
  .storybook/deprecated/cyclebutton/cyclebutton.stories.js
  .storybook/modes/index.js
  .storybook/package.json
  .storybook/preview.js
  .storybook/types/global.js
  .storybook/types/index.js
  components/accordion/stories/template.js
  components/actionbutton/stories/template.js
  components/actionmenu/stories/template.js
  components/assetcard/stories/template.js
  components/avatar/stories/template.js
  components/button/stories/template.js
  components/calendar/stories/template.js
  components/card/stories/template.js
  components/checkbox/stories/template.js
  components/colorarea/stories/template.js
  components/colorhandle/stories/template.js
  components/colorloupe/stories/template.js
  components/colorslider/stories/template.js
  components/dialog/stories/template.js
  components/popover/stories/template.js
  components/radio/stories/template.js
  components/rating/stories/template.js
  components/slider/stories/template.js
  components/swatch/stories/template.js
  components/textfield/stories/template.js
  components/thumbnail/stories/template.js
  components/underlay/stories/template.js
Labels: size-1 XS, run_vrt, storybook

#2930 fix(storybook): harden typography loading
  .changeset/green-geese-prove.md
  .storybook/assets/base.css
  .storybook/assets/index.css
  .storybook/decorators/language.js
  .storybook/loaders/font-loader.js
  .storybook/manager.js
  .storybook/package.json
  .storybook/preview-head.html
  .storybook/preview.js
  .storybook/project.json
Labels: size-2 S, run_vrt, storybook, ready-for-review

#2956 chore: remove unused typekit.js artifact from storybook
  .storybook/assets/typekit.js
Labels: size-1 XS, skip_vrt, storybook, ready-for-review

#2938 chore(build): update component builder to use modules; suppresses stylelint notice on build
  .github/workflows/lint.yml
  .storybook/project.json
  nx.json
  package.json
  site/project.json
  tokens/project.json
  ui-icons/project.json
Labels: build, skip_vrt, ready-for-review
