Repository adobe/spectrum-css, pull requests merged in 2025-07, with the labels that each got.

#3979 fix(azure-preview-workflow): update resource url to remove + use same token pattern
  .github/workflows/publish-site.yml
Labels: skip_vrt, ready-for-review

#4039 fix(lint-staged): remove conflicting flag for prettier command
  lint-staged.config.js
Labels: size-2 S, skip_vrt, ready-for-review

#4044 fix(tooltip,textfield,sidenav): update deprecated css
  .changeset/chubby-mirrors-wish.md
  components/sidenav/index.css
  components/tooltip/index.css
Labels: bug, size-1 XS, S2

#4056 chore(deps): remove unused @nx/devkit dependency
  package.json
  yarn.lock
Labels: dependencies, size-1 XS, skip_vrt, ready-for-review, low priority, skip_lint

#3694 chore: custom changesets plugin
  .changeset/config.json
  .github/workflows/development.yml
  plugins/changesets-changelog-github/index.js
  plugins/changesets-changelog-github/package.json
  plugins/changesets-changelog-github/project.json
  plugins/changesets-changelog-github/test.js
  yarn.lock
Labels: size-2 S, ready-for-review

#4003 feat(tabs): migrate to spectrum 2
  .changeset/fresh-kings-slide.md
  .changeset/ripe-toys-invent.md
  components/tabs/dist/metadata.json
  components/tabs/index.css
  components/tabs/stories/tabs.stories.js
  components/tabs/stories/tabs.test.js
  components/tabs/stories/template.js
  tokens/custom/large-vars.css
  tokens/custom/medium-vars.css
Labels: size-3 M, ready-for-review, S2

#4092 chore(deps): remove unused node-gyp
  .yarnrc.yml
  package.json
  yarn.lock
Labels: dependencies, size-1 XS, skip_vrt, ready-for-review, low priority, skip_lint
