Repository adobe/spectrum-css, pull requests merged in 2025-02, with the labels that each got.

#3395 feat(breadcrumb)!: spectrum 2 migration
  .changeset/fresh-crabs-deliver.md
  components/breadcrumb/dist/metadata.json
  components/breadcrumb/index.css
  components/breadcrumb/package.json
  components/breadcrumb/stories/breadcrumb.stories.js
  components/breadcrumb/stories/breadcrumb.test.js
  components/breadcrumb/stories/template.js
  yarn.lock
Labels: size-3 M, ready-for-review, S2

#3246 feat(illustratedmessage): adding new s2 tokens, horizontal layout, vrts
  .changeset/beige-dragons-tickle.md
  components/dropzone/dist/metadata.json
  components/dropzone/index.css
  components/dropzone/stories/dropzone.stories.js
  components/dropzone/stories/template.js
  components/illustratedmessage/dist/metadata.json
  components/illustratedmessage/index.css
  components/illustratedmessage/stories/illustratedmessage.stories.js
  components/illustratedmessage/stories/illustratedmessage.test.js
  components/illustratedmessage/stories/template.js
Labels: ready-for-review, S2

#3534 fix: index-theme system mappings bug [CSS-1114]
  .changeset/tender-doors-retire.md
  tasks/component-builder.js
  tasks/component-reporter.js
Labels: bug, size-2 S, skip_vrt, ready-for-review, high priority

#3528 feat(storybook): remove @adobe/spectrum-token dep from storybook
  .changeset/dry-falcons-exist.md
  .storybook/blocks/ColorPalette.jsx
  .storybook/blocks/Layouts.jsx
  .storybook/blocks/PropertiesTable.jsx
  .storybook/blocks/Swatches.jsx
  .storybook/blocks/ThemeContainer.jsx
  .storybook/blocks/Typography.jsx
  .storybook/blocks/utilities.js
  .storybook/guides/color_palette.mdx
  .storybook/manager.js
  .storybook/package.json
  package.json
  postcss.config.js
  tools/bundle/package.json
  tools/bundle/postcss.config.js
  tools/bundle/src/index.css.json
  tools/bundle/tasks/bundler.js
  yarn.lock
Labels: size-2 S, skip_vrt, storybook, ready-for-review

#2605 feat: add css minification output
  .changeset/early-badgers-wash.md
  .changeset/slow-waves-eat.md
  .github/actions/file-diff/index.js
  .github/actions/file-diff/utilities.js
  tasks/component-builder.js
Labels: size-3 M, build, skip_vrt, ready-for-review, low priority

#3543 fix(swatch): adjust s2 corner rounding
  .changeset/light-impalas-march.md
  components/swatch/dist/metadata.json
  components/swatch/index.css
  components/swatch/themes/spectrum-two.css
  components/swatch/themes/spectrum.css
Labels: size-1 XS, run_vrt, ready-for-review, S2

#3539 fix(textfield): vertically center invalid icon
  .changeset/healthy-windows-push.md
  components/textfield/dist/metadata.json
  components/textfield/index.css
  components/textfield/themes/spectrum-two.css
  components/textfield/themes/spectrum.css
Labels: size-1 XS, run_vrt, ready-for-review, S2

#3540 fix(actionbutton): fast follows
  .changeset/quick-hairs-walk.md
  components/actionbutton/dist/metadata.json
  components/actionbutton/index.css
  components/actionbutton/themes/express.css
  components/actionbutton/themes/spectrum-two.css
  components/actionbutton/themes/spectrum.css
Labels: bug, size-2 S, ready-to-merge

#3523 feat(contextualhelp): add mod to allow max-width
  .changeset/spicy-boats-repair.md
  components/contextualhelp/dist/metadata.json
  components/contextualhelp/index.css
  components/contextualhelp/stories/contextualhelp.stories.js
Labels: run_vrt, ready-for-review

#3553 chore(popover): add missing metadata update from build
  components/popover/dist/metadata.json
Labels: size-1 XS, ready-for-review

#3550 fix(button): revert primary button content color
  .changeset/metal-bees-bake.md
  components/button/themes/spectrum.css
Labels: size-1 XS, run_vrt, ready-to-merge, fast-follows

#3562 chore(dialog): use isOpen type for open control
  components/dialog/stories/dialog.stories.js
Labels: documentation, size-1 XS, skip_vrt, ready-for-review

#3559 docs(splitview): add guidelines link
  components/splitview/package.json
Labels: documentation, size-1 XS, skip_vrt

#3564 fix(storybook): remove workspace dependency references
  .changeset/ten-owls-beam.md
  .storybook/package.json
  yarn.lock
Labels: size-1 XS, skip_vrt, storybook, ready-for-review

#3566 feat(popover): overflow bug on Safari
  .changeset/perfect-worms-march.md
  components/popover/dist/metadata.json
  components/popover/index.css
Labels: bug, run_vrt, ready-for-review

#3568 test(combobox): corrects cases where open combobox stories and testing previews could overlap adjacent components
  components/combobox/stories/combobox.stories.js
  components/combobox/stories/combobox.test.js
Labels: size-1 XS, run_vrt, ready-for-review

#3577 chore: add adobe namespace to unpublished monorepo root
  package.json
  yarn.lock
Labels: size-1 XS, tech debt, skip_vrt, ready-for-review

#3547 fix(swatch): adjust disabled icon color across themes
  .changeset/fast-hats-worry.md
  components/swatch/dist/metadata.json
  components/swatch/index.css
  components/swatch/stories/template.js
  components/swatch/themes/spectrum-two.css
  components/swatch/themes/spectrum.css
Labels: bug, run_vrt, storybook, ready-for-review, S2

#3557 feat(divider): S2 migration
  .changeset/slow-eyes-lay.md
  components/divider/dist/metadata.json
  components/divider/index.css
  components/divider/stories/divider.stories.js
  components/divider/stories/divider.test.js
  components/divider/stories/template.js
Labels: size-2 S, skip_vrt, ready-for-review, S2

#3578 chore: add constraints and bundler logic to precommit
  README.md
  components/commons/package.json
  package.json
  tools/bundle/package.json
  tools/bundle/project.json
  tools/bundle/src/index.css
  tools/bundle/tasks/bundler.js
  yarn.config.cjs
  yarn.lock
Labels: dependencies, size-2 S, skip_vrt, ready-for-review

#3536 fix(picker,infieldbutton): updates custom properties for background/border colors
  .changeset/nervous-penguins-matter.md
  components/infieldbutton/dist/metadata.json
  components/infieldbutton/themes/spectrum-two.css
  components/picker/dist/metadata.json
  components/picker/index.css
  components/picker/themes/spectrum-two.css
  components/stepper/dist/metadata.json
  components/stepper/index.css
  components/stepper/themes/spectrum-two.css
Labels: bug, size-1 XS, skip_vrt, ready-to-merge

#3390 feat(colorwheel): S2 migration
  .changeset/giant-windows-smoke.md
  components/colorwheel/dist/metadata.json
  components/colorwheel/index.css
  components/colorwheel/stories/colorwheel.stories.js
  components/colorwheel/stories/colorwheel.test.js
  components/colorwheel/stories/template.js
Labels: size-2 S, skip_vrt, ready-for-review, S2

#3588 chore: run formatting on all packages as a refresh
  .storybook/CHANGELOG.md
  .storybook/decorators/context.js
  .storybook/decorators/helpers.js
  .storybook/decorators/icon-sprites.js
  .storybook/decorators/language.js
  .storybook/decorators/testing-preview.js
  .storybook/decorators/utilities.js
  .storybook/main.js
  .storybook/modes/index.js
  .storybook/project.json
  plugins/postcss-add-theming-layer/package.json
  plugins/postcss-property-rollup/package.json
  plugins/stylelint-no-missing-var/package.json
Labels: size-1 XS, skip_vrt, ready-for-review

#3573 fix(checkbox): update box color to neutral in s2
  .changeset/odd-seahorses-hunt.md
  components/checkbox/dist/metadata.json
  components/checkbox/themes/spectrum-two.css
  components/checkbox/themes/spectrum.css
Labels: size-2 S, run_vrt, ready-for-review, high priority, fast-follows

#3581 fix(menu): move s1/express focus indicator to right side for rtl
  .changeset/green-ghosts-collect.md
  components/menu/dist/metadata.json
  components/menu/index.css
Labels: size-1 XS, run_vrt, ready-to-merge

#3575 fix(textfield): update border and background color
  .changeset/fast-hats-worry.md
  .changeset/strong-falcons-switch.md
  components/textfield/themes/spectrum-two.css
  components/textfield/themes/spectrum.css
Labels: size-2 S, run_vrt, ready-for-review, high priority, fast-follows
