Repository adobe/spectrum-css, pull requests merged in 2025-01, with the labels that each got.

#3467 chore(caniuse-lite): dependency update
  yarn.lock
Labels: dependencies, skip_vrt, ready-for-review

#3474 fix: use new tag to hide storybook foundations stories
  .changeset/plenty-trees-act.md
  .storybook/foundations/corner-rounding/action-button-corner-rounding.stories.js
  .storybook/foundations/corner-rounding/checkbox-corner-rounding.stories.js
  .storybook/foundations/corner-rounding/corner-rounding.stories.js
  .storybook/foundations/down-state/button-down-state.stories.js
  .storybook/foundations/down-state/checkbox-down-state.stories.js
  .storybook/foundations/drop-shadow/drop-shadow.stories.js
Labels: ready-for-review, S2

#3475 fix: restore undefined custom properties [part 5]
  .changeset/hip-spies-try.md
  components/datepicker/index.css
  components/datepicker/metadata/metadata.json
  components/rating/index.css
  components/rating/metadata/metadata.json
  components/sidenav/index.css
  components/sidenav/metadata/metadata.json
  components/slider/index.css
  components/slider/metadata/metadata.json
  components/switch/index.css
  components/switch/metadata/metadata.json
Labels: ready-for-review, S2

#3444 fix(slider): adjust label width
  .changeset/itchy-poets-battle.md
  components/slider/index.css
Labels: bug, size-1 XS, skip_vrt, ready-for-review

#3471 fix(textfield,menu,tag,toast,tabs,well,popover): define custom props
  .changeset/ten-lizards-work.md
  components/menu/index.css
  components/menu/metadata/metadata.json
  components/popover/index.css
  components/popover/metadata/metadata.json
  components/tabs/index.css
  components/tabs/metadata/metadata.json
  components/tag/index.css
  components/tag/metadata/metadata.json
  components/textfield/index.css
  components/textfield/metadata/metadata.json
  components/toast/index.css
  components/toast/metadata/metadata.json
  components/well/index.css
  components/well/metadata/metadata.json
Labels: ready-for-review, S2

#3466 build: update to latest yarn
  .yarn/releases/yarn-4.1.1.cjs
  .yarn/releases/yarn-4.6.0.cjs
  .yarnrc.yml
  package.json
Labels: build, skip_vrt, ready-for-review

#3453 fix(colorloupe): adds correct disabled styles
  .changeset/slow-dogs-yawn.md
  components/colorloupe/index.css
  components/colorloupe/metadata/metadata.json
Labels: bug, size-1 XS, run_vrt

#3483 docs(avatar): update sizing documentation
  components/avatar/stories/avatar.stories.js
Labels: documentation, size-1 XS, skip_vrt, S2

#3490 fix: resolve buggy line numbers display in addon
  .storybook/preview.js
Labels: skip_vrt, ready-for-review

#3488 feat(tokens): remove components from token build
  .changeset/clean-doors-fail.md
  .changeset/olive-poets-love.md
  .github/actions/file-diff/index.js
  tasks/component-builder.js
  tasks/component-reporter.js
  tokens/custom-express/dark-vars.css
  tokens/custom-express/darkest-vars.css
  tokens/custom-express/global-vars.css
  tokens/custom-express/large-vars.css
  tokens/custom-express/light-vars.css
  tokens/custom-express/medium-vars.css
  tokens/custom-spectrum/dark-vars.css
  tokens/custom-spectrum/darkest-vars.css
  tokens/custom-spectrum/global-vars.css
  tokens/custom-spectrum/large-vars.css
  tokens/custom-spectrum/light-vars.css
  tokens/custom-spectrum/medium-vars.css
  tokens/dist/css/dark-vars.css
  tokens/dist/css/darkest-vars.css
  tokens/dist/css/express/custom-large-vars.css
  tokens/dist/css/express/custom-medium-vars.css
  tokens/dist/css/express/custom-vars.css
  tokens/dist/css/express/dark-vars.css
  tokens/dist/css/express/darkest-vars.css
  tokens/dist/css/express/global-vars.css
  tokens/dist/css/express/index.css
  tokens/dist/css/express/large-vars.css
  tokens/dist/css/express/light-vars.css
  tokens/dist/css/express/medium-vars.css
  tokens/dist/css/global-vars.css
  tokens/dist/css/large-vars.css
  tokens/dist/css/light-vars.css
  tokens/dist/css/medium-vars.css
  tokens/dist/css/spectrum/custom-large-vars.css
  tokens/dist/css/spectrum/custom-medium-vars.css
  tokens/dist/css/spectrum/custom-vars.css
  tokens/dist/css/spectrum/dark-vars.css
  tokens/dist/css/spectrum/darkest-vars.css
  tokens/dist/css/spectrum/global-vars.css
  tokens/dist/css/spectrum/index.css
  tokens/dist/css/spectrum/large-vars.css
  tokens/dist/css/spectrum/light-vars.css
  tokens/dist/css/spectrum/medium-vars.css
  tokens/dist/index.css
  tokens/postcss.config.js
  tokens/project.json
  tokens/tasks/token-rollup.js
Labels: breaking change, tokens, run_vrt, ready-for-review

#3477 feat(bundle): bundled css for dev/demos
  .changeset/honest-bulldogs-flow.md
  .changeset/stupid-rice-compare.md
  .storybook/blocks/ComponentDetails.jsx
  .storybook/blocks/PropertiesTable.jsx
  .storybook/blocks/utilities.js
  .storybook/manager.js
  .storybook/package.json
  .storybook/preview.js
  .storybook/project.json
  .stylelintignore
  README.md
  package.json
  postcss.config.js
  stylelint.config.js
  tasks/component-builder.js
  tasks/utilities.js
  tools/bundle/CHANGELOG.md
  tools/bundle/README.md
  tools/bundle/package.json
  tools/bundle/postcss.config.js
  tools/bundle/project.json
  tools/bundle/src/index.css
  tools/bundle/tasks/bundler.js
  yarn.lock
Labels: size-2 S, build, run_vrt, ready-for-review

#3440 chore(storybook): fix code loading on docs pages [CSS-1070]
  .changeset/famous-comics-run.md
  .storybook/decorators/context.js
  .storybook/decorators/helpers.js
  .storybook/decorators/language.js
  .storybook/decorators/testing-preview.js
  .storybook/decorators/underlay.js
  .storybook/decorators/utilities.js
  .storybook/main.js
  .storybook/package.json
  .storybook/preview-head.html
  .storybook/preview.js
  components/actionbar/stories/actionbar.test.js
  components/actionbutton/stories/template.js
  components/avatar/stories/avatar.test.js
  components/calendar/stories/template.js
  components/coachindicator/stories/coachindicator.test.js
  components/coachmark/stories/coachmark.test.js
  components/combobox/stories/combobox.stories.js
  components/datepicker/stories/datepicker.stories.js
  components/datepicker/stories/datepicker.test.js
  components/dialog/stories/dialog.test.js
  components/dropindicator/stories/dropindicator.test.js
  components/icon/stories/template.js
  components/menu/stories/template.js
  components/miller/stories/miller.test.js
  components/modal/stories/modal.test.js
  components/opacitycheckerboard/stories/opacitycheckerboard.test.js
  components/popover/stories/popover.test.js
  components/statuslight/stories/statuslight.test.js
  components/swatch/stories/template.js
  components/treeview/stories/template.js
  components/treeview/stories/treeview.test.js
  yarn.lock
Labels: size-3 M, run_vrt, storybook, high priority

#3458 feat(storybook)!: update chromatic add-on to latest version
  .changeset/tasty-pigs-tickle.md
  .env.example
  .storybook/blocks/ColorPalette.jsx
  .storybook/blocks/ComponentDetails.jsx
  .storybook/blocks/Layouts.jsx
  .storybook/blocks/PropertiesTable.jsx
  .storybook/blocks/Swatches.jsx
  .storybook/blocks/ThemeContainer.jsx
  .storybook/blocks/Typography.jsx
  .storybook/blocks/index.js
  .storybook/main.js
  .storybook/package.json
  .storybook/preview.js
  .storybook/templates/DocumentationTemplate.mdx
  package.json
  tasks/chromatic-config-creation.sh
  yarn.lock
Labels: dependencies, storybook, ready-for-review, s1

#3507 docs(combobox): remove separate tab focus for nested pickerbutton
  components/combobox/stories/template.js
  components/pickerbutton/stories/template.js
Labels: size-1 XS, ready-for-review

#3511 fix: use updated project url for logo link
  .storybook/package.json
Labels: size-1 XS, skip_vrt, storybook, ready-for-review

#3497 chore(tokens): use spectrum-tokens@13.0.0-beta.56
  .changeset/tame-wasps-shake.md
  tokens/dist/css/global-vars.css
  tokens/dist/css/index.css
  tokens/dist/index.css
  tokens/package.json
  yarn.lock
Labels: size-1 XS, skip_vrt, ready-for-review, S2

#3359 fix(stylelint): addresses remaining stylelint violations
  .changeset/clever-otters-mix.md
  .github/workflows/lint.yml
  components/assetcard/index.css
  components/assetcard/themes/express.css
  components/assetcard/themes/spectrum.css
  components/calendar/index.css
  components/calendar/metadata/metadata.json
  components/card/index.css
  components/card/metadata/metadata.json
  components/checkbox/index.css
  components/colorarea/index.css
  components/infieldbutton/index.css
  components/infieldbutton/metadata/metadata.json
  components/logicbutton/index.css
  components/modal/index.css
  components/modal/metadata/metadata.json
  components/progressbar/index.css
  components/radio/index.css
  components/radio/metadata/metadata.json
  components/stepper/index.css
  components/stepper/metadata/metadata.json
  components/stepper/themes/spectrum.css
  components/table/index.css
  components/table/metadata/metadata.json
  components/tooltip/index.css
  components/underlay/index.css
  stylelint.config.js
Labels: size-3 M, run_vrt, ready-for-review

#3514 chore: spectrum-two fixes
  components/picker/stories/picker.stories.js
  components/picker/stories/template.js
  components/tooltip/stories/template.js
Labels: bug, size-1 XS, ready-for-review, S2

#3380 feat(progress-circle): migrating s2 tokens, refactor markup to use SVG element
  .changeset/itchy-kids-travel.md
  components/progresscircle/animation.css
  components/progresscircle/dist/metadata.json
  components/progresscircle/index.css
  components/progresscircle/stories/progresscircle.stories.js
  components/progresscircle/stories/progresscircle.test.js
  components/progresscircle/stories/template.js
Labels: ready-for-review, S2

#3525 fix: resolve s2 branch build errors
  components/opacitycheckerboard/stories/template.js
Labels: size-1 XS, ready-for-review

#3424 feat(colorslider): S2 migration
  .changeset/serious-clouds-jam.md
  components/colorslider/dist/metadata.json
  components/colorslider/index.css
  components/colorslider/stories/colorslider.stories.js
  components/colorslider/stories/colorslider.test.js
  components/colorslider/stories/template.js
Labels: size-2 S, skip_vrt, ready-for-review, S2

#3347 feat(dialog): s2 takeover dialog migration
  .changeset/modern-chairs-sit.md
  components/dialog/dist/metadata.json
  components/dialog/index.css
  components/dialog/stories/dialog.stories.js
  components/dialog/stories/dialog.test.js
  components/dialog/stories/template.js
  components/modal/dist/metadata.json
  components/modal/index.css
  tokens/custom/large-vars.css
  tokens/custom/medium-vars.css
  tokens/dist/css/index.css
  tokens/dist/css/large-vars.css
  tokens/dist/css/medium-vars.css
  tokens/dist/index.css
Labels: size-2 S, skip_vrt, ready-for-review, S2

#3530 fix(menu): focus indicator styles fixed for S2
  .changeset/funny-pants-perform.md
  components/menu/dist/metadata.json
  components/menu/index.css
  components/menu/stories/menu.stories.js
  components/menu/stories/menu.test.js
  components/menu/stories/template.js
  components/menu/themes/spectrum-two.css
  components/menu/themes/spectrum.css
Labels: bug, size-2 S, run_vrt, ready-for-review, S2

#3529 feat(tokens): export json, remove duplicate file generation
  .changeset/mean-adults-scream.md
  .github/workflows/compare-results.yml
  .gitignore
  .storybook/blocks/ThemeContainer.jsx
  .vscode/settings.json
  postcss.config.js
  tasks/templates/compare-listing.njk
  tasks/templates/diff-preview.njk
  tokens/dist/css/dark-vars.css
  tokens/dist/css/global-vars.css
  tokens/dist/css/index.css
  tokens/dist/css/large-vars.css
  tokens/dist/css/light-vars.css
  tokens/dist/css/medium-vars.css
  tokens/dist/index.css
  tokens/package.json
  tokens/project.json
  tokens/tasks/token-rollup.js
  tools/bundle/package.json
  tools/bundle/project.json
  tools/bundle/src/index.css
  tools/bundle/tasks/bundler.js
  yarn.lock
Labels: size-2 S, build, skip_vrt, ready-for-review

#3365 feat(popover): migrate s2 popover
  .changeset/itchy-shrimps-help.md
  .changeset/rotten-meals-share.md
  .changeset/twenty-ravens-divide.md
  components/coachmark/dist/metadata.json
  components/coachmark/index.css
  components/picker/dist/metadata.json
  components/picker/index.css
  components/picker/stories/template.js
  components/popover/dist/metadata.json
  components/popover/index.css
  components/popover/stories/popover.stories.js
  components/popover/stories/popover.test.js
  components/popover/stories/template.js
Labels: skip_vrt, ready-for-review, S2
