Repository adobe/spectrum-css, pull requests merged in 2025-03, with the labels that each got.

#3596 fix(readme): corrects path to css illutration png in readme
  README.md
Labels: skip_vrt

#3571 feat: simplify fallback of ui icon size numbers
  components/actionbutton/stories/template.js
  components/button/stories/button.test.js
  components/icon/stories/icon.mdx
  components/icon/stories/icon.stories.js
  components/icon/stories/template.js
  components/icon/stories/utilities.js
  components/menu/stories/template.js
  components/search/stories/template.js
  components/swatch/stories/template.js
  components/textfield/stories/template.js
  components/treeview/stories/template.js
Labels: ready-for-review, S2

#3594 chore(stepper): update default variant, key focus state in s2
  .changeset/shaggy-dragons-visit.md
  components/stepper/themes/spectrum-two.css
Labels: size-1 XS, run_vrt, ready-to-merge, fast-follows

#3599 chore: regenerate yarn.lock after merge
  yarn.lock
Labels: skip_vrt, ready-for-review

#3600 fix(button): adjust static primary outline button border colors
  .changeset/curvy-bottles-boil.md
  components/button/dist/metadata.json
  components/button/themes/spectrum-two.css
Labels: run_vrt, ready-for-review, S2, fast-follows

#3429 feat(dropzone): migrating new S2 tokens, more spaced out dashed lines, more illustrations
  .changeset/big-beds-care.md
  .storybook/assets/images/dropzone-illustration.png
  components/dropzone/dist/metadata.json
  components/dropzone/index.css
  components/dropzone/stories/dropzone.stories.js
  components/dropzone/stories/dropzone.test.js
  components/dropzone/stories/template.js
Labels: ready-for-review, S2

#3603 fix(lint-staged): add yarn command to lint staged to ensure the lock file is updated
  lint-staged.config.js
Labels: size-2 S, skip_vrt, ready-for-review

#3608 fix(lint-staged): add yarn command to lint staged to ensure the lock file is updated
  lint-staged.config.js
Labels: skip_vrt, ready-for-review

#3607 chore(picker): updated border-color for open not hover state of picker
  .changeset/angry-boats-walk.md
  components/picker/dist/metadata.json
  components/picker/themes/spectrum-two.css
Labels: run_vrt

#3612 fix(constraints): run constraints and update lockfile
  .github/workflows/release.yml
  lint-staged.config.js
  package.json
Labels: size-3 M, skip_vrt

#3606 feat(actionbutton): use closer to s2 colors in spectrum-two theme
  .changeset/tall-pens-lay.md
  components/actionbutton/dist/metadata.json
  components/actionbutton/index.css
  components/actionbutton/themes/spectrum-two.css
  components/actionbutton/themes/spectrum.css
Labels: ready-for-review, fast-follows

#3613 fix(button): adjust s2 static colors
  .changeset/kind-mails-collect.md
  components/button/dist/metadata.json
  components/button/themes/spectrum-two.css
Labels: skip_vrt, ready-to-merge, fast-follows

#3614 fix(slider): corrects contrast bug caused by template default arg
  components/slider/stories/template.js
Labels: size-2 S, skip_vrt, ready-for-review

#3570 feat(link): new typography tokens, focus color and design, WHCM focus state
  .changeset/tasty-eagles-draw.md
  components/link/dist/metadata.json
  components/link/index.css
  components/link/stories/link.stories.js
  components/link/stories/link.test.js
  components/link/stories/template.js
Labels: ready-for-review, S2

#3621 fix(stepper): focus/focus+hover/keyboardFocus border colors
  .changeset/sharp-spiders-complain.md
  components/stepper/themes/spectrum-two.css
Labels: ready-for-review, fast-follows

#3611 fix(slider): offset variant border radius bug fix
  .changeset/rude-jokes-judge.md
  components/slider/dist/metadata.json
  components/slider/index.css
Labels: bug, size-1 XS, ready-for-review

#3609 fix(combobox): border color fast follows swc-582
  .changeset/breezy-crews-guess.md
  components/combobox/dist/metadata.json
  components/combobox/index.css
  components/combobox/themes/express.css
  components/combobox/themes/spectrum-two.css
  components/combobox/themes/spectrum.css
Labels: size-1 XS, run_vrt, ready-for-review, fast-follows

#3626 chore: patch tj-actions vulnerability
  .github/workflows/development.yml
Labels: size-1 XS, skip_vrt, github_actions, ready-for-review, high priority

#3624 fix(alertbanner): change system variable from spectrum to legacy
  .changeset/metal-eels-protect.md
  components/alertbanner/themes/spectrum.css
Labels: size-1 XS, ready-for-review

#3625 test(checkbox): add more coverage for checkbox
  components/checkbox/stories/checkbox.stories.js
  components/checkbox/stories/checkbox.test.js
  components/checkbox/stories/template.js
  components/form/stories/form.stories.js
Labels: testing, run_vrt, ready-for-review

#3617 fix(checkbox): corrects invalid+checked+hover background color
  .changeset/blue-wasps-talk.md
  components/checkbox/dist/metadata.json
  components/checkbox/index.css
Labels: bug, ready-for-review

#3527 feat: update postcss tooling
  .changeset/dirty-gorillas-warn.md
  .changeset/silent-pandas-film.md
  .storybook/main.js
  .storybook/package.json
  .storybook/postcss.config.js
  components/assetlist/dist/metadata.json
  components/clearbutton/dist/metadata.json
  components/dial/dist/metadata.json
  components/menu/dist/metadata.json
  components/slider/dist/metadata.json
  nx.json
  package.json
  plugins/postcss-add-theming-layer/package.json
  plugins/stylelint-no-missing-var/package.json
  plugins/stylelint-no-unknown-custom-properties/package.json
  plugins/stylelint-no-unused-custom-properties/package.json
  plugins/stylelint-theme-alignment/package.json
  postcss.config.js
  stylelint.config.js
  tools/bundle/package.json
  yarn.lock
Labels: dependencies, size-3 M, feature, run_vrt, storybook, ready-for-review, low priority

#3633 chore: merge branch 'main' into spectrum-two
  .github/workflows/development.yml
  components/actionbutton/CHANGELOG.md
  components/alertbanner/CHANGELOG.md
  components/checkbox/CHANGELOG.md
  components/checkbox/dist/metadata.json
  components/checkbox/index.css
  components/checkbox/stories/checkbox.stories.js
  components/checkbox/stories/checkbox.test.js
  components/checkbox/stories/template.js
  components/combobox/CHANGELOG.md
  components/combobox/dist/metadata.json
  components/combobox/index.css
  components/form/stories/form.stories.js
  components/search/CHANGELOG.md
  components/slider/CHANGELOG.md
  components/slider/dist/metadata.json
  components/slider/index.css
  components/stepper/CHANGELOG.md
Labels: ready-for-review

#3555 feat(radio): adding new colors, type, and size tokens, invalid state, WHCM
  .changeset/angry-needles-behave.md
  components/helptext/stories/template.js
  components/radio/dist/metadata.json
  components/radio/index.css
  components/radio/stories/radio.stories.js
  components/radio/stories/radio.test.js
  components/radio/stories/template.js
Labels: size-3 M, ready-to-merge, S2

#3630 fix(pickerbutton): correct states' background colors
  .changeset/kind-walls-fix.md
  components/pickerbutton/dist/metadata.json
  components/pickerbutton/themes/spectrum-two.css
Labels: size-1 XS, ready-for-review, fast-follows

#2669 feat(actionbutton): s2 migration
  .changeset/chilled-peaches-enjoy.md
  components/actionbutton/dist/metadata.json
  components/actionbutton/index.css
  components/actionbutton/stories/actionbutton.stories.js
  components/actionbutton/stories/actionbutton.test.js
  components/actionbutton/stories/template.js
Labels: run_vrt, ready-for-review, S2

#3640 fix: downgrade storybook and set to fixed minor version 8.4
  .storybook/main.js
  .storybook/package.json
  yarn.lock
Labels: ready-for-review

#3644 fix(actionbutton): reimplement support for border-radius mod
  .changeset/friendly-pumas-switch.md
  components/actionbutton/dist/metadata.json
  components/actionbutton/index.css
  components/actionbutton/themes/spectrum-two.css
  components/actionbutton/themes/spectrum.css
Labels: bug, ready-for-review
