Repository adobe/spectrum-css, pull requests merged in 2025-08, with the labels that each got.

#4112 docs(.git*): removes remaining reference(s) to Netlify in the codebase
  .github/GUIDE.md
  .github/workflows/development.yml
  .github/workflows/production.yml
  .gitignore
Labels: size-2 S, skip_vrt, ready-for-review

#4113 fix: minor linting updates
  .changeset/ready-apes-pull.md
  components/alertbanner/dist/metadata.json
  components/alertbanner/index.css
  components/assetcard/index.css
  components/breadcrumb/index.css
  components/calendar/index.css
  components/card/dist/metadata.json
  components/card/index.css
  components/coachmark/dist/metadata.json
  components/coachmark/index.css
  components/colorhandle/index.css
  components/colorslider/index.css
  components/colorwheel/index.css
  components/combobox/dist/metadata.json
  components/combobox/index.css
  components/datepicker/index.css
  components/dial/index.css
  components/dropzone/index.css
  components/inlinealert/index.css
  components/page/index.css
  components/sidenav/index.css
  components/stepper/dist/metadata.json
  components/stepper/index.css
  components/thumbnail/index.css
  components/treeview/index.css
  components/underlay/index.css
  components/well/index.css
  stylelint.config.js
Labels: size-1 XS, run_vrt, ready-for-review

#4108 chore: align build with s2 branch
  .github/QUICK-START.md
  .github/actions/file-diff/README.md
  .github/scripts/build-preview-urls-comment.js
  .github/scripts/comment-or-update.js
  .github/workflows/development.yml
  .github/workflows/lint.yml
  .github/workflows/production.yml
  .github/workflows/publish-site.yml
  .github/workflows/vrt.yml
Labels: size-2 S, build, run_vrt, ready-for-review

#4115 feat(search): collapsed search
  .changeset/long-carrots-sleep.md
  components/search/dist/metadata.json
  components/search/index.css
  components/search/stories/search.stories.js
  components/search/stories/search.test.js
  components/search/stories/template.js
Labels: size-5 L, ready-for-review, S2

#4155 docs(storybook): add documentation to filter s2 components
  .storybook/guides/s2_migration.mdx
Labels: documentation, size-1 XS, ready-for-review, S2

#4163 chore(spectrum-two): config ci updates
  .github/workflows/development.yml
  .github/workflows/lint.yml
Labels: size-1 XS, skip_vrt, github_actions, ready-for-review, S2

#4164 chore(main): github actions minor ci updates
  .github/GUIDE.md
  .github/renovate.json
  .github/workflows/build.yml
  .github/workflows/compare-results.yml
  .github/workflows/development.yml
  .github/workflows/lint.yml
  .github/workflows/production.yml
  .github/workflows/publish-site.yml
  .github/workflows/release-snapshot.yml
  .github/workflows/release.yml
  .github/workflows/vrt.yml
  .gitignore
Labels: size-1 XS, skip_vrt, github_actions, ready-for-review, low priority

#4139 fix(accordion): clean up spacing issues
  .changeset/sweet-badgers-melt.md
  components/accordion/dist/metadata.json
  components/accordion/index.css
  components/accordion/stories/accordion.stories.js
  components/accordion/stories/accordion.test.js
Labels: size-2 S, run_vrt, ready-to-merge, S2

#4174 chore(popover): adjust/enhance popover spacing by default [CSS-845]
  .changeset/modern-times-happen.md
  components/actionbar/stories/template.js
  components/actionmenu/stories/template.js
  components/alertdialog/stories/alertdialog.stories.js
  components/coachindicator/stories/template.js
  components/coachmark/stories/coachmark.stories.js
  components/coachmark/stories/template.js
  components/combobox/stories/combobox.stories.js
  components/combobox/stories/combobox.test.js
  components/combobox/stories/template.js
  components/contextualhelp/stories/contextualhelp.stories.js
  components/contextualhelp/stories/contextualhelp.test.js
  components/contextualhelp/stories/template.js
  components/datepicker/stories/datepicker.stories.js
  components/dialog/stories/dialog.stories.js
  components/picker/stories/picker.stories.js
  components/picker/stories/template.js
  components/popover/index.css
  components/popover/stories/popover.stories.js
  components/popover/stories/popover.test.js
  components/popover/stories/template.js
  components/tray/stories/tray.stories.js
Labels: bug, size-2 S, run_vrt, storybook, low priority, S2
