Repository adobe/spectrum-css, pull requests merged in 2025-06, with the labels that each got.

#3792 feat(picker): refactoring template markup, testing token passthroughs
  .changeset/open-squids-refuse.md
  components/picker/dist/metadata.json
  components/picker/index.css
  components/picker/stories/picker.stories.js
  components/picker/stories/picker.test.js
  components/picker/stories/template.js
Labels: size-5 L, ready-for-review, S2

#3908 fix(progress-bar + meter): Adjust progressbar styles, story and template to support proper width token and sizes for medium and large variants
  .changeset/mighty-pigs-accept.md
  components/meter/dist/metadata.json
  components/meter/index.css
  components/progressbar/dist/metadata.json
  components/progressbar/index.css
  components/progressbar/stories/progressbar.stories.js
  components/progressbar/stories/template.js
Labels: size-3 M, skip_vrt, ready-for-review

#3684 feat(accordion): spectrum 2 migration
  .changeset/chatty-lands-attack.md
  components/accordion/dist/metadata.json
  components/accordion/index.css
  components/accordion/stories/accordion.stories.js
  components/accordion/stories/accordion.test.js
  components/accordion/stories/template.js
Labels: size-5 L, ready-for-review, S2

#3909 feat(contextual-help): S2 migration
  .changeset/legal-lands-warn.md
  components/contextualhelp/dist/metadata.json
  components/contextualhelp/index.css
  components/contextualhelp/stories/contextualhelp.stories.js
  components/contextualhelp/stories/contextualhelp.test.js
  components/contextualhelp/stories/template.js
Labels: size-5 L, skip_vrt, ready-for-review

#3965 fix(popover): restores drop shadow for nested popovers
  .changeset/gold-cats-hide.md
  components/popover/dist/metadata.json
  components/popover/index.css
Labels: size-5 L, skip_vrt

#3966 feat(taggroup): spectrum 2 migration
  .changeset/public-facts-boil.md
  components/taggroup/dist/metadata.json
  components/taggroup/index.css
  components/taggroup/stories/taggroup.stories.js
  components/taggroup/stories/taggroup.test.js
  components/taggroup/stories/template.js
Labels: size-3 M, skip_vrt, ready-for-review, S2

#3968 feat(meter): s2 migration, full corner radius, help text
  .changeset/sour-donuts-go.md
  components/meter/dist/metadata.json
  components/meter/index.css
  components/meter/stories/meter.stories.js
  components/meter/stories/meter.test.js
  components/meter/stories/template.js
  components/progressbar/dist/metadata.json
  components/progressbar/index.css
  components/progressbar/stories/template.js
Labels: size-3 M, ready-for-review, S2
