Repository adobe/spectrum-css, pull requests merged in 2025-05, with the labels that each got.

#3689 chore(popover): fix dismissible spelling
  components/popover/stories/popover.stories.js
  components/popover/stories/popover.test.js
Labels: size-1 XS, skip_vrt, ready-for-review, S2

#3691 chore: update with latest from main
  .github/workflows/development.yml
Labels: size-1 XS, skip_vrt, github_actions, ready-for-review, S2

#3690 docs: add storybook migrated badge
  .storybook/preview.js
  components/actionbutton/stories/actionbutton.stories.js
  components/actiongroup/stories/actiongroup.stories.js
  components/alertbanner/stories/alertbanner.stories.js
  components/avatar/stories/avatar.stories.js
  components/breadcrumb/stories/breadcrumb.stories.js
  components/button/stories/button.stories.js
  components/buttongroup/stories/buttongroup.stories.js
  components/checkbox/stories/checkbox.stories.js
  components/closebutton/stories/closebutton.stories.js
  components/coachmark/stories/coachmark.stories.js
  components/colorarea/stories/colorarea.stories.js
  components/colorhandle/stories/colorhandle.stories.js
  components/colorloupe/stories/colorloupe.stories.js
  components/colorslider/stories/colorslider.stories.js
  components/colorwheel/stories/colorwheel.stories.js
  components/dial/stories/dial.stories.js
  components/dialog/stories/dialog.stories.js
  components/divider/stories/divider.stories.js
  components/dropzone/stories/dropzone.stories.js
  components/fieldgroup/stories/fieldgroup.stories.js
  components/fieldlabel/stories/fieldlabel.stories.js
  components/form/stories/form.stories.js
  components/helptext/stories/helptext.stories.js
  components/icon/stories/icon.stories.js
  components/illustratedmessage/stories/illustratedmessage.stories.js
  components/infieldbutton/stories/infieldbutton.stories.js
  components/infieldprogresscircle/stories/infieldprogresscircle.stories.js
  components/inlinealert/stories/inlinealert.stories.js
  components/link/stories/link.stories.js
  components/opacitycheckerboard/stories/opacitycheckerboard.stories.js
  components/pagination/stories/pagination.stories.js
  components/picker/stories/picker.stories.js
  components/popover/stories/popover.stories.js
  components/progressbar/stories/progressbar.stories.js
  components/progresscircle/stories/progresscircle.stories.js
  components/radio/stories/radio.stories.js
  components/rating/stories/rating.stories.js
  components/search/stories/search.stories.js
  components/statuslight/stories/statuslight.stories.js
  components/switch/stories/switch.stories.js
  components/textfield/stories/textarea.stories.js
  components/textfield/stories/textfield.stories.js
  components/thumbnail/stories/thumbnail.stories.js
  components/toast/stories/toast.stories.js
  components/tooltip/stories/tooltip.stories.js
Labels: documentation, size-2 S, ready-for-review, S2

#3687 fix(button,statuslight,picker,etc): address regressions in migrated components
  .changeset/breezy-impalas-push.md
  .changeset/cute-pillows-stand.md
  .changeset/fair-coins-buy.md
  .changeset/fresh-spoons-try.md
  .changeset/late-worms-reply.md
  .changeset/smart-spoons-sneeze.md
  .changeset/warm-loops-guess.md
  components/button/dist/metadata.json
  components/button/index.css
  components/button/stories/button.stories.js
  components/button/stories/button.test.js
  components/button/stories/template.js
  components/colorarea/stories/template.js
  components/floatingactionbutton/index.css
  components/link/dist/metadata.json
  components/link/index.css
  components/logicbutton/index.css
  components/picker/dist/metadata.json
  components/picker/index.css
  components/picker/stories/picker.stories.js
  components/picker/stories/template.js
  components/statuslight/dist/metadata.json
  components/statuslight/index.css
  components/switch/dist/metadata.json
  components/switch/index.css
Labels: bug, size-1 XS, skip_vrt, ready-for-review, S2

#3693 docs(action bar): add migrated tag
  components/actionbar/stories/actionbar.stories.js
Labels: size-1 XS, ready-for-review, S2

#3681 feat(stepper): s2 number field/stepper migration
  .changeset/itchy-waves-work.md
  components/form/stories/form.stories.js
  components/infieldbutton/stories/template.js
  components/stepper/dist/metadata.json
  components/stepper/index.css
  components/stepper/package.json
  components/stepper/stories/stepper.stories.js
  components/stepper/stories/stepper.test.js
  components/stepper/stories/template.js
  components/textfield/stories/template.js
Labels: size-3 M, skip_vrt, ready-for-review, S2

#3678 chore: swap dependabot for renovate
  .changeset/config.json
  .github/GUIDE.md
  .github/dependabot.yml
  .github/renovate.json
  .github/workflows/vrt.yml
  nx.json
  yarn.config.cjs
Labels: size-2 S, skip_vrt, github_actions, ready-for-review

#3718 chore: merge latest main into spectrum-two
  .changeset/config.json
  .github/GUIDE.md
  .github/dependabot.yml
  .github/renovate.json
  .github/workflows/vrt.yml
  .yarn/releases/yarn-4.6.0.cjs
  .yarn/releases/yarn-4.9.1.cjs
  .yarnrc.yml
  nx.json
  package.json
  yarn.config.cjs
  yarn.lock
Labels: size-2 S, skip_vrt, github_actions, ready-for-review, S2

#3686 feat(menu): spectrum 2 migration
  .changeset/strong-pianos-work.md
  components/menu/dist/metadata.json
  components/menu/index.css
  components/menu/stories/menu.stories.js
  components/menu/stories/menu.test.js
  components/menu/stories/template.js
Labels: size-5 L, ready-to-merge, S2

#3677 feat(swatch+swatchgroup): S2 migration
  .changeset/proud-schools-reply.md
  components/swatch/dist/metadata.json
  components/swatch/index.css
  components/swatch/stories/swatch.stories.js
  components/swatch/stories/swatch.test.js
  components/swatch/stories/template.js
  components/swatchgroup/dist/metadata.json
  components/swatchgroup/index.css
  components/swatchgroup/stories/swatchgroup.stories.js
  components/swatchgroup/stories/swatchgroup.test.js
  components/swatchgroup/stories/template.js
  tokens/custom/dark-vars.css
  tokens/custom/global-vars.css
  tokens/custom/light-vars.css
  tokens/dist/json/tokens.json
  tokens/style-dictionary.config.js
  tokens/utilities/css-border-rounding-transform.js
  tokens/utilities/index.js
Labels: size-8 XL, skip_vrt, ready-for-review

#3752 chore(swatch,menu,swatchgroup): fix reverted metadata assets
  components/menu/dist/metadata.json
  components/swatch/dist/metadata.json
  components/swatchgroup/dist/metadata.json
Labels: size-1 XS, ready-for-review, S2

#3740 feat(badge): S2 migration
  .changeset/serious-cameras-hammer.md
  components/badge/dist/metadata.json
  components/badge/index.css
  components/badge/stories/badge.stories.js
  components/badge/stories/badge.test.js
  components/badge/stories/template.js
Labels: size-1 XS, ready-for-review, S2

#3735 docs(menu): add migrated status badge
  components/menu/stories/menu.stories.js
Labels: size-1 XS, skip_vrt, ready-for-review, S2

#3759 chore: renovate config to bump packages with updates
  .github/renovate.json
Labels: size-1 XS, ready-for-review

#3777 chore: merge latest updates from main
  .github/actions/file-diff/package.json
  .github/workflows/development.yml
  package.json
  tokens/project.json
  yarn.lock
Labels: size-1 XS, ready-for-review, S2

#3725 feat(alert dialog): S2 migration
  .changeset/lemon-flowers-poke.md
  components/alertdialog/dist/metadata.json
  components/alertdialog/index.css
  components/alertdialog/stories/alertdialog.stories.js
  components/alertdialog/stories/alertdialog.test.js
  components/alertdialog/stories/template.js
  tokens/custom/large-vars.css
  tokens/custom/medium-vars.css
Labels: size-5 L, size-8 XL, skip_vrt, ready-for-review

#3871 chore(swatch): updates the add swatch icon to use the ui rather than workflow icon
  .changeset/dirty-melons-look.md
  components/swatch/stories/template.js
Labels: size-2 S, skip_vrt, ready-for-review
