Repository adobe/spectrum-css, pull requests merged in 2025-04, with the labels that each got.

#3628 feat(helptext): S2 migration
  .changeset/wild-lemons-spend.md
  components/helptext/dist/metadata.json
  components/helptext/index.css
  components/helptext/stories/helptext.stories.js
  components/helptext/stories/template.js
Labels: size-1 XS, ready-for-review, S2

#3412 feat(coachmark): S2 migration
  .changeset/lemon-weeks-work.md
  .changeset/nice-cows-shout.md
  components/coachmark/dist/metadata.json
  components/coachmark/index.css
  components/coachmark/stories/coachmark.stories.js
  components/coachmark/stories/coachmark.test.js
  components/coachmark/stories/template.js
  tokens/custom/large-vars.css
  tokens/custom/medium-vars.css
Labels: size-8 XL, skip_vrt, ready-for-review, S2

#3641 fix(tooltip): restore negative and informative semantic variants
  .changeset/stale-pans-carry.md
  components/tooltip/dist/metadata.json
  components/tooltip/index.css
  components/tooltip/stories/template.js
  components/tooltip/stories/tooltip.stories.js
  components/tooltip/stories/tooltip.test.js
Labels: size-3 M, skip_vrt, ready-for-review

#3636 docs(button,icon): remove MDX files
  components/button/stories/button.mdx
  components/button/stories/button.stories.js
  components/icon/stories/icon.mdx
  components/icon/stories/icon.stories.js
  components/icon/stories/template.js
  components/typography/stories/typography.stories.js
Labels: documentation, skip_vrt, ready-for-review

#3615 fix(infield-button): updated border color for disabled state
  .changeset/popular-trains-sniff.md
  components/infieldbutton/dist/metadata.json
  components/infieldbutton/index.css
  components/infieldbutton/themes/spectrum-two.css
  components/infieldbutton/themes/spectrum.css
Labels: size-1 XS, run_vrt, ready-for-review, fast-follows

#3662 fix(button): reduce mod interception
  .changeset/stale-baboons-shake.md
  components/button/dist/metadata.json
  components/button/index.css
  components/button/themes/express.css
  components/button/themes/spectrum-two.css
  components/button/themes/spectrum.css
Labels: bug, size-2 S, run_vrt, ready-for-review

#3665 fix(button): s1/express static outline variant content color
  .changeset/happy-frogs-flash.md
  components/button/themes/spectrum.css
Labels: bug, size-1 XS, run_vrt, ready-for-review

#2673 feat(search): s2 migration
  .changeset/old-goats-chew.md
  .changeset/shaggy-schools-sing.md
  components/clearbutton/stories/clearbutton.stories.js
  components/clearbutton/stories/template.js
  components/search/dist/metadata.json
  components/search/index.css
  components/search/stories/search.stories.js
  components/search/stories/search.test.js
  components/search/stories/template.js
  tokens/custom/global-vars.css
Labels: skip_vrt, ready-for-review, S2

#3655 fix: reduce excess stylelint warnings from bundle module
  stylelint.config.js
Labels: ready-for-review

#3652 fix(fieldlabel): prevent required icon from appearing on its own line when wrapping
  .changeset/honest-animals-stop.md
  components/fieldlabel/index.css
  components/fieldlabel/stories/fieldlabel.stories.js
  components/fieldlabel/stories/template.js
Labels: size-3 M, skip_vrt, ready-for-review

#3669 feat(tokens,card): update to @adobe/spectrum-tokens@13.3.0
  .changeset/puny-kids-rhyme.md
  .changeset/spotty-bats-deny.md
  .markdownlint.json
  .prettierignore
  components/card/dist/metadata.json
  components/card/index.css
  components/card/stories/card.stories.js
  components/card/stories/card.test.js
  components/card/stories/template.js
  tokens/dist/json/tokens.json
  tokens/package.json
  tokens/project.json
  yarn.lock
Labels: size-1 XS, feature, tokens, skip_vrt, ready-for-review, low priority, S2

#3627 feat(rating): S2 migration
  .changeset/eighty-terms-lead.md
  components/rating/dist/metadata.json
  components/rating/index.css
  components/rating/stories/rating.stories.js
  components/rating/stories/rating.test.js
  components/rating/stories/template.js
  tokens/custom/large-vars.css
  tokens/custom/medium-vars.css
Labels: size-5 L, skip_vrt, S2

#2500 feat(tokens): support latest style-dictionary build
  .gitattributes
  .github/workflows/build.yml
  .github/workflows/development.yml
  .storybook/blocks/utilities.js
  .storybook/package.json
  nx.json
  package.json
  plugins/postcss-add-theming-layer/index.js
  plugins/stylelint-no-missing-var/package.json
  plugins/stylelint-no-unknown-custom-properties/package.json
  plugins/stylelint-no-unused-custom-properties/package.json
  plugins/stylelint-theme-alignment/package.json
  postcss.config.js
  tasks/component-builder.js
  tasks/component-compare.js
  tasks/component-reporter.js
  tasks/templates/compare-listing.njk
  tasks/templates/diff-preview.njk
  tasks/utilities.js
  tokens/dist/json/tokens.json
  tokens/package.json
  tokens/postcss.config.js
  tokens/project.json
  tokens/style-dictionary.config.js
  tokens/tasks/token-rollup.js
  tokens/utilities/attribute-sets-transform.js
  tokens/utilities/css-font-open-type-transform.js
  tokens/utilities/css-sets-formatter.js
  tokens/utilities/data-json-formatter.js
  tokens/utilities/index.js
  tokens/utilities/json-sets-formatter.js
  tokens/utilities/name-kebab-transform.js
  tokens/utilities/style-dictionary.utils.js
  tools/bundle/postcss.config.js
  tools/bundle/project.json
  tools/bundle/src/index.css
  tools/bundle/src/index.css.json
  tools/bundle/tasks/bundler.js
  yarn.lock
Labels: size-5 L, tokens, skip_vrt, ready-for-review, low priority

#3531 feat(checkbox/group): s2 token migration, control spacing, subtle color changes
  .changeset/six-donuts-march.md
  components/checkbox/dist/metadata.json
  components/checkbox/index.css
  components/checkbox/stories/checkbox.stories.js
  components/checkbox/stories/checkbox.test.js
  components/checkbox/stories/template.js
Labels: ready-for-review, S2

#3679 chore: update s2 branch with latest
  .gitattributes
  .github/workflows/build.yml
  .github/workflows/development.yml
  .storybook/blocks/utilities.js
  .storybook/package.json
  nx.json
  package.json
  plugins/postcss-rgb-mapping/CHANGELOG.md
  plugins/postcss-rgb-mapping/README.md
  plugins/postcss-rgb-mapping/expected/basic.css
  plugins/postcss-rgb-mapping/expected/modern.css
  plugins/postcss-rgb-mapping/fixtures/basic.css
  plugins/postcss-rgb-mapping/index.js
  plugins/postcss-rgb-mapping/package.json
  plugins/stylelint-no-missing-var/package.json
  plugins/stylelint-no-unknown-custom-properties/package.json
  plugins/stylelint-no-unused-custom-properties/package.json
  postcss.config.js
  tasks/component-builder.js
  tasks/component-compare.js
  tasks/component-reporter.js
  tasks/templates/compare-listing.njk
  tasks/templates/diff-preview.njk
  tasks/utilities.js
  tokens/dist/json/tokens.json
  tokens/package.json
  tokens/postcss.config.js
  tokens/project.json
  tokens/style-dictionary.config.js
  tokens/tasks/token-rollup.js
  tokens/utilities/attribute-sets-transform.js
  tokens/utilities/css-font-open-type-transform.js
  tokens/utilities/css-sets-formatter.js
  tokens/utilities/data-json-formatter.js
  tokens/utilities/index.js
  tokens/utilities/json-sets-formatter.js
  tokens/utilities/name-kebab-transform.js
  tokens/utilities/style-dictionary.utils.js
  tools/bundle/postcss.config.js
  tools/bundle/project.json
  tools/bundle/src/index.css
  tools/bundle/src/index.css.json
  tools/bundle/tasks/bundler.js
  yarn.lock
Labels: ready-for-review, S2

#3642 feat(infield-button): new s2 migration
  .changeset/true-shrimps-dream.md
  components/infieldbutton/dist/metadata.json
  components/infieldbutton/index.css
  components/infieldbutton/stories/infieldbutton.stories.js
  components/infieldbutton/stories/infieldbutton.test.js
  components/infieldbutton/stories/template.js
  tokens/custom/large-vars.css
  tokens/custom/medium-vars.css
Labels: size-3 M, ready-for-review, S2

#3680 chore: harden recently updated scripts
  .github/workflows/development.yml
  .storybook/assets/base.css
  tasks/clean-up-after-migration.sh
  tokens/utilities/data-json-formatter.js
Labels: size-2 S, ready-for-review

#3643 feat(toast): S2 migration
  .changeset/red-kiwis-flash.md
  components/toast/dist/metadata.json
  components/toast/index.css
  components/toast/stories/template.js
  components/toast/stories/toast.stories.js
  components/toast/stories/toast.test.js
Labels: size-5 L, skip_vrt, ready-for-review

#3656 feat(touch-action): adding touch action none to draggable components
  .changeset/thick-ears-win.md
  components/colorarea/index.css
  components/colorhandle/index.css
  components/colorslider/index.css
  components/colorwheel/index.css
  components/slider/index.css
Labels: size-2 S, ready-for-review, S2
